
### Menu Options
locList.addLoc("basic","Básico","pt")
locList.addLoc("improved","Melhorado","pt")
locList.addLoc("enhanced","Aumentado","pt")
locList.addLoc("advanced","Avançado","pt")
locList.addLoc("Superior","Superior","pt")
locList.addLoc("optimal","Ótimo","pt")

locList.addLoc("edict_cgm_menu_edict_desc","Este edito abre o menu principal do CGM.","pt")
locList.addLoc("edict_cgm_menu_edict","Abrir Menu CGM","pt")
locList.addLoc("cgm_buildings_text","Core Game Mechanics: Construções","pt")
locList.addLoc("cgm_main_menu_close_desc","Fechar Menu","pt")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_name","Ativar Conteúdo de Construção do CGM","pt")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_desc","Esta opção ativa as alterações do CGM às construções de recursos. Todas as construções de recursos originais, por ex. Redes de Mineração ou Usinas de Energia, são automaticamente substituídas e qualquer tecnologia que esteja faltando é automaticamente fornecida. \n Tenha em atenção que esta opção está disponível apenas durante o início do jogo e não pode ser desfeita.","pt")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_name","Manter Construções originais","pt")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_desc","Esta opção define o jogo para usar as construções de recursos originais. Nenhuma alteração é feita às construções ou tecnologias existentes. Escolher esta opção irá desbloquear mais opções de configuração.","pt")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_name","Ativar Revisões às Estatísticas das Construções","pt")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_desc","Esta opção ativa as revisões às estatísticas das construções. Algumas construções ficarão com créditos de recursos diferentes, modificadores de planetas, etc. em relação ao original. Esta opção pode ser ativada / desativada ao seu critério a qualquer momento durante o jogo.","pt")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_name","Desativar Revisões às Estatísticas das Construções","pt")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_desc","Esta opção desativa as revisões às estatísticas das construções. Todas as construções do conteúdo original terão as estatísticas originais.","pt")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_name","Configuração de Construções $advanced$","pt")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_desc","Esta opção abre o menu Configuração de Construções $advanced$, que lhe permite alterar o custo e o tempo de construção de categorias de construções específicas.","pt")
locList.addLoc("cgm_main_menu_title","Menu Principal CGM","pt")
locList.addLoc("cgm_main_menu_desc","Neste menu poderá escolher se deseja jogar usando as construções de recursos originais ou as versões CGM.\n\nTenha atenção: se ativar conteúdo CGM o mod irá converter automaticamente as construções originais existentes para as novas versões CGM. Isto não pode ser desfeito.","pt")
locList.addLoc("cgm_main_menu_header","Core Game Mechanics","pt")
locList.addLoc("cgm_main_menu_close_name","Fechar Menu","pt")

#Allow Stuff

locList.addLoc("requires_non_machine_empire_capital","Requer construção da Capital Imperial.","pt")
locList.addLoc("requires_building_capital_0","Requer qualquer construção de Capital Planetária.","pt")
locList.addLoc("requires_building_capital_0_or_hab","Requer qualquer construção de Capital.","pt")
locList.addLoc("requires_building_hab_capital","Requer qualquer construção de Capital de Habitat ou Capital Imperial.","pt")
locList.addLoc("requires_building_capital_2_or_hab","Requer qualquer construção de Capital de Habitat.","pt")
locList.addLoc("requires_energy_tile","Requer Energia £energy no quadrado.","pt")
locList.addLoc("requires_minerals_tile","Requer Minerais £minerals no quadrado.","pt")
locList.addLoc("requires_food_tile","Requer Comida £food no quadrado.","pt")
locList.addLoc("requires_engineering_research_tile","Requer Engenharia £engineering no quadrado.","pt")
locList.addLoc("requires_physics_research_tile","Requer Física £physics no quadrado.","pt")
locList.addLoc("requires_society_research_tile","Requer Sociedade £society no quadrado.","pt")
locList.addLoc("requires_megastructure_node_tile","Requer Nó de Megaestrutura £megastructure_node no quadrado.","pt")

locList.addLoc("tech_biofuel_refining_1_desc","Matéria orgânica complexa pode ser convertida em uma fonte barata de combustível. Embora não seja tão eficiente quanto a síntese de isótopos radioativos, a matéria orgânica é significativamente mais comum.","pt")
locList.addLoc("tech_biofuel_refining_1","Refino de biocombustíveis $basic$","pt")
locList.addLoc("tech_biofuel_refining_2_desc","A potência do nosso biocombustível pode ser aumentada usando bactérias geneticamente modificadas que segregam um pseudo-óleo potente.","pt")
locList.addLoc("tech_biofuel_refining_2","Refino de biocombustíveis $enhanced$","pt")
locList.addLoc("tech_biofuel_refining_3_desc","Ao manipular moléculas orgânicas em uma escala minúscula, somos capazes de criar biocombustível artificial significativamente mais potente.","pt")
locList.addLoc("tech_biofuel_refining_3","Refino de biocombustíveis $advanced$","pt")
locList.addLoc("tech_biofuel_refining_4_desc","Novos métodos de síntese nos permitem criar um biocombustível em estado sólido, o que torna o produto final mais transportável e significativamente mais potente.","pt")
locList.addLoc("tech_biofuel_refining_4","Condensação de Biocombustível Artificial","pt")
locList.addLoc("tech_biofuel_refining_5_desc","O uso de máquinas de escala picométrica permite-nos sintetizar biocombustível quase sem desperdício.","pt")
locList.addLoc("tech_biofuel_refining_5","Síntese de Biocombustíveis $optimal$","pt")
locList.addLoc("tech_power_plant_5_desc","O uso da catálise quântica permite-nos gerar imensas quantidades de energia.","pt")
locList.addLoc("tech_power_plant_5","Síntese Isotópica Quântica","pt")
locList.addLoc("tech_mining_network_5_desc","O uso de brocas gravitônicas permite-nos penetrar com precisão e rapidez em estratos profundos.","pt")
locList.addLoc("tech_mining_network_5","Mineração $superior$","pt")
locList.addLoc("tech_superior_agriculture_desc","O uso de solo nanoativo permite-nos cultivar uma quantidade incrível de culturas.","pt")
locList.addLoc("tech_superior_agriculture","Agricultura $superior$","pt")
locList.addLoc("tech_biolab_4_desc","No que diz respeito à temporalidade como um único continuum holístico, podemos tratar fenômenos aparentemente díspares como fundamentalmente interconectados.","pt")
locList.addLoc("tech_biolab_4","Psico-História Holística","pt")
locList.addLoc("tech_physics_lab_4_desc","A teoria chegou ao ponto em que podemos começar a procurar a teoria do ômega, que é capaz de descrever não apenas nosso universo, mas também outras dimensões.","pt")
locList.addLoc("tech_physics_lab_4","Teoria Omega","pt")
locList.addLoc("tech_engineering_lab_4_desc","Nossas ciências materiais alcançam o ponto em que somos capazes de explorar a criação de nanoware de auto-modelagem e auto-concepção.","pt")
locList.addLoc("tech_engineering_lab_4","Teoria da Matéria-Inteligente","pt")
locList.addLoc("tech_agricultural_processing_1_desc","As nanotecnologias originalmente desenvolvidas para melhorar as nossas bases estelares nos permitem aumentar significativamente a produção das nossas fazendas e hidropônicas.","pt")
locList.addLoc("tech_agricultural_processing_1","Processamento Agrícola $advanced$","pt")
locList.addLoc("tech_agricultural_processing_2_desc","O uso de tecnologias de robotica avançada permite-nos automatizar e melhorar ainda mais o processamento de matéria orgânica em alimentos de consumo.","pt")
locList.addLoc("tech_agricultural_processing_2","Processamento Agrícola $superior$","pt")
locList.addLoc("tech_hyperstorage_1","Hyper Armazenamento","pt")
locList.addLoc("tech_hyperstorage_1_desc","O armazenamento formulado como um problema científico levará ao surgimento de um novo paradigma.","pt")
locList.addLoc("tech_hyperstorage_2","Hyper Armazenamento $advanced$","pt")
locList.addLoc("tech_hyperstorage_2_desc","Avanços recentes no estudo do armazenamento nanométrico podem aumentar substancialmente a eficiência de nossas instalações de Hyper Armazenamento.","pt")
locList.addLoc("tech_hyperstorage_3","Hyper Armazenamento $superior$","pt")
locList.addLoc("tech_hyperstorage_3_desc","Avanços recentes no estudo da entropia nos permitem aumentar ainda mais a eficiência de nossas instalações de Hyper Armazenamento.","pt")

### Strategic Resources

locList.addLoc("sr_megastructure_node","Nó de Megaestrutura","pt")
locList.addLoc("sr_megastructure_node_desc","Nós de Megaestrutura representam junções estruturais onde a matriz de energia interna da megaestrutura pode ser expandida.","pt")


### Modifiers

locList.addLoc("capital_building_build_cost_mult","Multiplicador de Custo de construção de Capitais","pt")
locList.addLoc("capital_building_construction_speed_mult","Multiplicador de Velocidade de construção de Capitais","pt")
locList.addLoc("empire_unique_building_build_cost_mult","Multiplicador de Custo de construção de Construções Imperiais Únicas","pt")
locList.addLoc("empire_unique_building_construction_speed_mult","Multiplicador de Velocidade de construção de Construções Imperiais Únicas","pt")
locList.addLoc("planet_unique_building_build_cost_mult","Multiplicador de Custo de construção de Construções Planetárias Únicas","pt")
locList.addLoc("planet_unique_building_construction_speed_mult","Multiplicador de Velocidade de construção de Construções Planetárias Únicas","pt")
locList.addLoc("military_building_build_cost_mult","Multiplicador de Custo de construção de Construções Militares","pt")
locList.addLoc("military_building_construction_speed_mult","Multiplicador de Velocidade de construção de Construções Militares","pt")
locList.addLoc("standard_resource_building_build_cost_mult","Multiplicador de Custo de construção de Construções Básicas de Recursos","pt")
locList.addLoc("standard_resource_building_construction_speed_mult","Multiplicador de Velocidade de construção de Construções Básicas de Recursos","pt")
locList.addLoc("research_resource_building_build_cost_mult","Multiplicador de Custo de construção de Construções de Recursos de Pesquisa","pt")
locList.addLoc("research_resource_building_construction_speed_mult","Multiplicador de Velocidade de construção de Construções de Recursos de Pesquisa","pt")
locList.addLoc("unity_resource_building_build_cost_mult","Multiplicador de Custo de construção de Construções de Recursos de Unidade","pt")
locList.addLoc("unity_resource_building_construction_speed_mult","Multiplicador de Velocidade de construção de Construções de Recursos de Unidade","pt")
locList.addLoc("special_resource_building_build_cost_mult","Multiplicador de Custo de construção de Construções Especiais de Recursos","pt")
locList.addLoc("special_resource_building_construction_speed_mult","Multiplicador de Velocidade de construção de Construções Especiais de Recursos","pt")
locList.addLoc("replicator_building_build_cost_mult","Multiplicador de Custo de construção de Construções de Replicadores","pt")
locList.addLoc("replicator_building_construction_speed_mult","Multiplicador de Velocidade de construção de Construções de Replicadores","pt")

### Triggered Planet Modifiers Keys

locList.addLoc("capital_3_resource_bonus_modifier","Bônus Capital Imperial N5","pt")
locList.addLoc("capital_3_resource_bonus_modifier_desc","Este é um bônus especial dado por construções de recursos de nível 5 em um planeta com capital de império.","pt")
locList.addLoc("power_plant_5_regular_capital_modifier","Bônus Usina V em Capital Imperial","pt")
locList.addLoc("power_plant_5_ringworld_capital_modifier","Bônus Usina V em Capital Imperial (Mundo em Anel)","pt")
locList.addLoc("mining_network_5_regular_capital_modifier","Bônus Rede de Mineração V em Capital Imperial","pt")
locList.addLoc("mining_network_5_ringworld_capital_modifier","Bônus Rede de Mineração V em Capital Imperial (Mundo em Anel)","pt")
locList.addLoc("hydroponics_farm_5_regular_capital_modifier","Bônus Fazenda Hidropônica V em Capital Imperial","pt")
locList.addLoc("hydroponics_farm_5_ringworld_capital_modifier","Bônus Fazenda Hidropônica V em Capital Imperial (Mundo em Anel)","pt")
locList.addLoc("engineering_facility_4_regular_capital_modifier","Bônus Instalação de Engenharia V em Capital Imperial","pt")
locList.addLoc("engineering_facility_4_ringworld_capital_modifier","Bônus Instalação de Engenharia V em Capital Imperial (Mundo em Anel)","pt")
locList.addLoc("physics_lab_4_regular_capital_modifier","Bônus Laboratório de Física V em Capital Imperial","pt")
locList.addLoc("physics_lab_4_ringworld_capital_modifier","Bônus Laboratório de Física V em Capital Imperial (Mundo em Anel)","pt")
locList.addLoc("biolab_4_regular_capital_modifier","Bônus Biolaboratório V em Capital Imperial","pt")
locList.addLoc("biolab_4_ringworld_capital_modifier","Bônus Biolaboratório V em Capital Imperial (Mundo em Anel)","pt")

### Building Localisations

locList.addLoc("mining_complex","Complexo Mineiro","pt")
locList.addLoc("mining_complex_desc","Complexos Mineiros são construções §Hrestringidas§! a quadrados que contenham minerais £minerals e só nestes podem ser construidos.\n Eles têm um crédito de produção base que depende do nível do Complexo Mineiro mais §H200%§! da quantidade de minerais £minerals presentes no quadrado onde está construído.","pt")
locList.addLoc("farming_complex","Complexo Agrícula","pt")
locList.addLoc("farming_complex_desc","Complexos Agrículas são construções §Hrestringidas§! a quadrados que contenham comida £food e só nestes podem ser construidos.\n Eles têm um crédito de produção base que depende do nível do Complexo Agrícula mais §H200%§! da quantidade de comida £food presente no quadrado onde está construído.","pt")
locList.addLoc("isotope_refinery","Refinaria de Isótopo","pt")
locList.addLoc("isotope_refinery_desc","Refinarias de Isótopo são construções §Hrestringidas§! a quadrados que contenham energia £energy e só nestes podem ser construidas.\n Elas têm um crédito de produção base que depende do nível da Refinaria de Isótopo mais §H200%§! da quantidade de energia £energy presente no quadrado onde está construída.","pt")
locList.addLoc("biofuel_refinery","Refinaria de Biocombustível","pt")
locList.addLoc("biofuel_refinery_desc","Refinarias de Biocombustível são construções §Hrestringidas§! a quadrados que contenham comida £food e só nestes podem ser construidas.\n Elas têm um crédito de produção base que depende do nível da Refinaria de Biocombustível mais §H100%§! da quantidade de comida £food presente no quadrado onde está construída convertida para energia £energy.","pt")
locList.addLoc("society_lab","Laboratório de Sociedade","pt")
locList.addLoc("society_lab_desc","Laboratórios de Sociedade são construções §Hrestringidas§! a quadrados que contenham pesquisa de sociedade £society e só nestes podem ser construidos.\n Eles têm um crédito de produção base que depende do nível do Laboratório de Sociedade mais §H200%§! da quantidade de pesquisa de sociedade £society presente no quadrado onde está construído.","pt")
locList.addLoc("physics_lab","Laboratório de Física","pt")
locList.addLoc("physics_lab_desc","Laboratórios de Física são construções §Hrestringidas§! a quadrados que contenham pesquisa de física £physics e só nestes podem ser construidos.\n Eles têm um crédito de produção base que depende do nível do Laboratório de Física mais §H200%§! da quantidade de pesquisa de física £physics presente no quadrado onde está construído.","pt")
locList.addLoc("engineering_lab","Laboratório de Engenharia","pt")
locList.addLoc("engineering_lab_desc","Laboratórios de Engenharia são construções §Hrestringidas§! a quadrados que contenham pesquisa de engenharia £engineering e só nestes podem ser construidos.\n Eles têm um crédito de produção base que depende do nível do Laboratório de Engenharia mais §H200%§! da quantidade de pesquisa de engenharia £engineering presente no quadrado onde está construído.","pt")
locList.addLoc("energy_matter_converter","Conversor de Energia-Matéria","pt")
locList.addLoc("energy_matter_converter_desc","Conversores de Energia-Matéria são construções especiais §Hrestringidas§! a quadrados que contenham um Nó de Megaestrutura £megastructure_node e só nestes podem ser construidos.\n Eles têm um crédito de produção fixo de §H+3§! minerais £minerals mas dão um poderoso bônus de adjacência de minerais £minerals que aumenta dependendo do número de pontos do nó de megaestrutura £megastructure_node no quadrado onde é construído, assim como o respectivo nível.","pt")
locList.addLoc("energy_conduit","Conduta de Energia","pt")
locList.addLoc("energy_conduit_desc","Condutas de Energia são construções especiais §Hrestringidas§! a quadrados que contenham um Nó de Megaestrutura £megastructure_node e só nestes podem ser construidas.\n Elas têm um crédito de produção fixo de §H+3§! energia £energy mas dão um poderoso bônus de adjacência de energia £energy que aumenta dependendo do número de pontos do nó de megaestrutura £megastructure_node no quadrado onde é construída, assim como o respectivo nível.","pt")
locList.addLoc("food_replicator","Replicador de Alimentos","pt")
locList.addLoc("food_replicator_desc","Replicadores de Alimentos são construções especiais §Hrestringidas§! a quadrados que contenham um Nó de Megaestrutura £megastructure_node e só nestes podem ser construidos.\n Eles têm um crédito de produção fixo de §H+3§! comida £food mas dão um poderoso bônus de adjacência de comida £food que aumenta dependendo do número de pontos do nó de megaestrutura £megastructure_node no quadrado onde é construído, assim como o respectivo nível.","pt")
locList.addLoc("computational_array","Matriz computacional","pt")
locList.addLoc("computational_array_desc","Matrizes computacionais são construções especiais §Hrestringidas§! a quadrados que contenham um Nó de Megaestrutura £megastructure_node e só nestes podem ser construidas.\n Elas têm um crédito de produção fixo de §H+1/+1/+1§! sociedade £society, física £physics e engenharia £engineering mas dão um poderoso bônus de adjacência para todas as construções de pesquisa que aumenta dependendo do número de pontos do nó de megaestrutura £megastructure_node no quadrado onde é construída, assim como o respectivo nível.","pt")
locList.addLoc("economic_district","Distrito Econômico","pt")
locList.addLoc("economic_district_desc","Distritos Econômicos são construções não-restringidas de produção de energia £energy. Estas construções representam centros de comércio e desenvolvimento econômico.\n Eles têm tanto um crédito de produção base como um crédito de produção fixo que aumenta com o nível do Distrito.","pt")
locList.addLoc("manufacturing_complex","Complexo Manufatureiro","pt")
locList.addLoc("manufacturing_complex_desc","Complexos Manufatureiros são construções não-restringidas de produção de minerais £minerals. Estas construções representam centros de produção e desenvolvimento industrial.\n Eles têm tanto um crédito de produção base como um crédito de produção fixo que aumenta com o nível do Complexo.","pt")
locList.addLoc("hydroponic_farm","Complexo Hidropônico","pt")
locList.addLoc("hydroponic_farm_desc","Complexos Hidropônicos são construções não-restringidas de produção de alimentos £food. Estas construções representam biosferas rigidamente controladas dedicadas à produção de alimentos.\n Eles têm tanto um crédito de produção base como um crédito de produção fixo que aumenta com o nível do Complexo.","pt")
locList.addLoc("sociological_campus","Campus de Sociologia","pt")
locList.addLoc("sociological_campus_desc","Campus de Sociologia são construções não-restringidas de pesquisa de sociedade £society. Estas construções representam centros de pesquisa e desenvolvimento científicos.\n Eles têm tanto um crédito de produção base como um crédito de produção fixo que aumenta com o nível do Campus.","pt")
locList.addLoc("physics_campus","Campus de Física","pt")
locList.addLoc("physics_campus_desc","Campus de Física são construções não-restringidas de pesquisa de física £physics. Estas construções representam centros de pesquisa e desenvolvimento científicos.\n Eles têm tanto um crédito de produção base como um crédito de produção fixo que aumenta com o nível do Campus.","pt")
locList.addLoc("engineering_campus","Campus de Engenharia","pt")
locList.addLoc("engineering_campus_desc","Campus de Engenharia são construções não-restringidas de pesquisa de engenharia £engineering. Estas construções representam centros de pesquisa e desenvolvimento científicos.\n Eles têm tanto um crédito de produção base como um crédito de produção fixo que aumenta com o nível do Campus.","pt")
locList.addLoc("agricultural_processor","Processador Agrícola","pt")
locList.addLoc("agricultural_processor_desc","Os complexos de Processamento Agrícula produzem alimentos £food por conta própria, mas mais importante, eles aumentam a produtividade de produtores de comida £food do planeta.","pt")
locList.addLoc("hyperstorage_facility","Instalação de Hyper Armazenamento","pt")
locList.addLoc("hyperstorage_facility_desc","Instalações de Hyper Armazenamento utilizam tecnologias de ponta de estase e manipulação de vácuo para armazenar materiais.\n Embora estas construções produzam alguns minerais £minerals para impérios maquinários ou minerais £minerals e comida £food para imérios orgânicos, sua principal vantagem aparece quando um império sofre um §RDéficit Mineral§!, §RDéficit Energético§!, ou no caso de impérios orgânicos, §RFome§!. Quando isto ocorre, a Instalação de Hyper Armazenamento começará a produzir grandes quantidades de até §Gdois recursos necessários§!.","pt")