
### Menu Options
locList.addLoc("basic","Базовый","rus")
locList.addLoc("improved","Улучшенный","rus")
locList.addLoc("enhanced","Расширенный","rus")
locList.addLoc("advanced","Продвинутый","rus")
locList.addLoc("Superior","Максимально Равитой","rus")
locList.addLoc("optimal","Оптимальный","rus")

locList.addLoc("edict_cgm_menu_edict_desc","Этот указ открывает главное меню CGM.","rus")
locList.addLoc("edict_cgm_menu_edict","Открыть Меню CGM","rus")
locList.addLoc("cgm_buildings_text","Core Game Mechanics: Здания","rus")
locList.addLoc("cgm_main_menu_close_desc","Закрыть меню","rus")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_name","Включить здания CGM","rus")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_desc","Эта опция подключает модификации ресурсов CGM. Все стандартные здания из базовой игры, такие как шахты и электростанции, автоматически заменяются и все недостающее технологии автоматически выдаются.\n Обратите внимание, эта опция доступна только в начале игры и не может быть отключена.","rus")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_name","Сохранить здания базовой игры","rus")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_desc","Эта опция сохраняет здания из базовой игры. Существующие здания и технологии остаются без изменений. Выбрав эту опцию, вы получите доступ к дополнительным настройкам.","rus")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_name","Подключить измененные параметры зданий","rus")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_desc","Эта опция подключает переработанные параметры зданий. Изменяет производимые ресурсы, планетарные модификаторы и так далее. Эту опцию можно включать и выключать во время игры на ваше усмотрение.","rus")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_name","Отключить переработанные параметры зданий","rus")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_desc","Эта опция отключает переработанные параметры зданий. Все здания из базовой игры вернутся к изначальным параметрам.","rus")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_name","Продвинутая настройка зданий","rus")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_desc","Эта опция открывает меню продвинутых настроек зданий, где вы сможете изменить стоимость и время постройки зданий конкретных типов.","rus")
locList.addLoc("cgm_main_menu_title","Главное меню CGM","rus")
locList.addLoc("cgm_main_menu_desc","В этом меню вы можете решить играть ли со ресурсодобывающими зданиями из базовой игры или из CGM.\n\nОбратите внимание: если вы подключите контент из CGM, мод конвертирует уже существующие здания. Это действие необратимо.","rus")
locList.addLoc("cgm_main_menu_header","Core Game Mechanics","rus")
locList.addLoc("cgm_main_menu_close_name","Закрыть меню","rus")

#Allow Stuff

locList.addLoc("requires_non_machine_empire_capital","На этой планете требуется $building_capital_3$.","rus")
locList.addLoc("requires_building_capital_0","На этой планете требуется любая сталица.","rus")
locList.addLoc("requires_building_capital_0_or_hab","На этой планете требуется любая столица.","rus")
locList.addLoc("requires_building_hab_capital","На этой планете требуется столица империи или столица орбитальной среды обитания.","rus")
locList.addLoc("requires_building_capital_2_or_hab","Требуется столица орбитальной среды обитания.","rus")
locList.addLoc("requires_energy_tile","На квадрате должна быть £energy энергия.","rus")
locList.addLoc("requires_minerals_tile","На квадрате должны быть £minerals минералы.","rus")
locList.addLoc("requires_food_tile","На квадрате должна быть £food еда.","rus")
locList.addLoc("requires_engineering_research_tile","На квадрате должны быть £engineering инженерные исследования.","rus")
locList.addLoc("requires_physics_research_tile","На квадрате должны быть £physics физически исследования.","rus")
locList.addLoc("requires_society_research_tile","На квадрате должны быть £society социальные исследования.","rus")
locList.addLoc("requires_megastructure_node_tile","На квадрате должен быть £megastructure_node мегаструктурный узел.","rus")

locList.addLoc("tech_biofuel_refining_1_desc","Сложные органические соединения можно превратить в источник дешёвого топлива. Хотя это и менее эффективно чем синтез радиоактивных изотопов, органические соединения более распространены.","rus")
locList.addLoc("tech_biofuel_refining_1","Базовая Очистка Биотоплива","rus")
locList.addLoc("tech_biofuel_refining_2_desc","Эффективность нашего биотоплива может быть повышена при помощи генетически модифицированных бактерий, выделяющих псевдо-нефть.","rus")
locList.addLoc("tech_biofuel_refining_2","Улучшенная Очистка Биотоплива","rus")
locList.addLoc("tech_biofuel_refining_3_desc","Манипулируя органическими соединениями на микроуровне, мы можем синтезировать намного более эффективное искусственное биотопливо.","rus")
locList.addLoc("tech_biofuel_refining_3","Продвинутый Синтез Биотоплива","rus")
locList.addLoc("tech_biofuel_refining_4_desc","Продвинутые методики синтеза позволяет нам создать твердое биотопливо, что облегчит перевозку конечного продукта и сделает его намного эффективнее.","rus")
locList.addLoc("tech_biofuel_refining_4","Искусственное Сгущение Биотоплива","rus")
locList.addLoc("tech_biofuel_refining_5_desc","Использование техники в пикометрическом масштабе делает возможным практически безотходное производство биотоплива.","rus")
locList.addLoc("tech_biofuel_refining_5","$optimal$ Синтез Биотоплива","rus")
locList.addLoc("tech_power_plant_5_desc","Использование квантового катализа позволит нам производить невероятное количество энергии.","rus")
locList.addLoc("tech_power_plant_5","Квантовый Синтез Изотопов","rus")
locList.addLoc("tech_mining_network_5_desc","Использование гравитонных дрелей позволяет точно и быстро проникать в глубокие слои.","rus")
locList.addLoc("tech_mining_network_5","Максимально Развитое Горное Дело","rus")
locList.addLoc("tech_superior_agriculture_desc","Использование наноактивного грунта позволит нам выращивать невероятные объёмы урожая.","rus")
locList.addLoc("tech_superior_agriculture","Максимально Развитое Сельское Хозяйство","rus")
locList.addLoc("tech_biolab_4_desc","Представив время единым холистическим континуумом, мы сможем рассматривать кажущиеся независимыми феномены как фундаментально связанные.","rus")
locList.addLoc("tech_biolab_4","Холистическая Психоистория","rus")
locList.addLoc("tech_physics_lab_4_desc","Теории дошли до отметки, где мы можем начать поискии омега-теории, способной описать не только нашу вселенную, но и другие измерения.","rus")
locList.addLoc("tech_physics_lab_4","Омега-Теория","rus")
locList.addLoc("tech_engineering_lab_4_desc","Наши исследования материалов дошли до отметки позволяющей нам создавать и использовать самоформирующиеся и саморазрабатывающиеся наноматериалы.","rus")
locList.addLoc("tech_engineering_lab_4","Теория Умной Материи","rus")
locList.addLoc("tech_agricultural_processing_1_desc","Нанотехнологии, изначально разработанные для развития наших космических станций, позволяют заметно увеличить урожайность ферм.","rus")
locList.addLoc("tech_agricultural_processing_1","Продвинутая Сельскохозяйственная Обработка","rus")
locList.addLoc("tech_agricultural_processing_2_desc","Использование продвинутых роботехнологий позволяет дальнейшую автоматизацию и развитие переработки органических материалов в пригодную для употребления пищу.","rus")
locList.addLoc("tech_agricultural_processing_2","Максимально Развитая Сельскохозяйственная Обработка","rus")
locList.addLoc("tech_hyperstorage_1","Гиперхранилища","rus")
locList.addLoc("tech_hyperstorage_1_desc","Хранение поднимает научные вопросы, которые ведут к новым парадигмам.","rus")
locList.addLoc("tech_hyperstorage_2","Продвинутые Гиперхранилища","rus")
locList.addLoc("tech_hyperstorage_2_desc","Недавние открытия в области нанометрического хранения могут значительно повысить эффективность наших гиперхранилищ.","rus")
locList.addLoc("tech_hyperstorage_3","Максимально Развитые Гиперхранилища","rus")
locList.addLoc("tech_hyperstorage_3_desc","Новые достижения в изучении энтропии позволят ещё сильнее увеличить эффективность гиперхранилищ.","rus")

### Strategic Resources

locList.addLoc("sr_megastructure_node","Мегаструктурный Узел","rus")
locList.addLoc("sr_megastructure_node_desc","Мегаструктурный узел представляет собой место, где энергетические системы мегаструктуры могут быть расширены.","rus")


### Modifiers

locList.addLoc("capital_building_build_cost_mult","Цена Столичных Зданий","rus")
locList.addLoc("capital_building_construction_speed_mult","Скорость Строительства Столичных Зданий","rus")
locList.addLoc("empire_unique_building_build_cost_mult","Цена Уникальных для Империи Зданий","rus")
locList.addLoc("empire_unique_building_construction_speed_mult","Скорость Строительства Уникальных для Империи Зданий","rus")
locList.addLoc("planet_unique_building_build_cost_mult","Цена Уникальных для Планеты Зданий","rus")
locList.addLoc("planet_unique_building_construction_speed_mult","Скорость Строительства Уникальных для Планеты Зданий","rus")
locList.addLoc("military_building_build_cost_mult","Цена Военных Зданий","rus")
locList.addLoc("military_building_construction_speed_mult","Скорость Строительства Военных Зданий","rus")
locList.addLoc("standard_resource_building_build_cost_mult","Цена Стандартных Ресурсопроизводящих Зданий","rus")
locList.addLoc("standard_resource_building_construction_speed_mult","Скорость Строительства Стандартных Ресурсопроизводящих Зданий","rus")
locList.addLoc("research_resource_building_build_cost_mult","Цена Научных Зданий","rus")
locList.addLoc("research_resource_building_construction_speed_mult","Скорость Строительства Научных Зданий","rus")
locList.addLoc("unity_resource_building_build_cost_mult","Цена Зданий Производящих Единство","rus")
locList.addLoc("unity_resource_building_construction_speed_mult","Скорость Строительства Зданий Производящих Единство","rus")
locList.addLoc("special_resource_building_build_cost_mult","Цена Специальных Ресурсных Зданий","rus")
locList.addLoc("special_resource_building_construction_speed_mult","Скорость Строительства Специальных Ресурсных Зданий","rus")
locList.addLoc("replicator_building_build_cost_mult","Цена Репликаторов","rus")
locList.addLoc("replicator_building_construction_speed_mult","Скорость Строительства Репликаторов","rus")