
### Menu Options
locList.addLoc("basic","Базовый","ru")
locList.addLoc("improved","Улучшенный","ru")
locList.addLoc("enhanced","Расширенный","ru")
locList.addLoc("advanced","Продвинутый","ru")
locList.addLoc("superior","Совершенный","ru")
locList.addLoc("optimal","Оптимальный","ru")

locList.addLoc("edict_cgm_menu_edict_desc","Этот указ открывает главное меню CGM.","ru")
locList.addLoc("edict_cgm_menu_edict","Открыть Меню CGM","ru")

locList.addLoc("edict_cgm_autobuild_decrease_spending","Уменьшить бюджет на автоматизированное строительство","ru")
locList.addLoc("edict_cgm_autobuild_decrease_spending_desc","","ru")
locList.addLoc("cgm_autobuild_decrease_spending_desc","Уменьшить процент от вашего ежемесячного дохода, идущего на автоматическое строительство на 5%. Current: [this.cgm_building_construction_percent]%","ru")
locList.addLoc("edict_cgm_autobuild_increase_spending","Увеличить бюджет на автоматизированное строительство","ru")
locList.addLoc("edict_cgm_autobuild_increase_spending_desc","","ru")
locList.addLoc("cgm_autobuild_increase_spending_desc","Увеличить процент от вашего ежемесячного дохода, идущего на автоматическое строительство на 5%. Current: [this.cgm_building_construction_percent]%","ru")

locList.addLoc("cgm_buildings_text","Core Game Mechanics: Здания","ru")
locList.addLoc("edict_cgm_enable_player_autobuild","Включить автоматизированное строительство","ru")
locList.addLoc("edict_cgm_sector_autobuild_only","Включить секторное автоматизированное строительство","ru")
locList.addLoc("edict_cgm_disable_player_autobuild","Выключить автоматизированное строительство","ru")
locList.addLoc("edict_cgm_enable_player_autobuild_desc","Каждый месяц забирает настраиваемый процент (по умолчанию 20%) вашего дохода в минералах и использует это при умном автоматическом строительстве зданий. Предпочитаются основные миры. Никакого влияния на ИИ или других игроков.","ru")
locList.addLoc("edict_cgm_sector_autobuild_only_desc","Каждый месяц забирает настраиваемый процент (по умолчанию 20%) вашего дохода в минералах и использует это при умном автоматическом строительстве зданий. Только для секторов. Никакого влияния на ИИ или других игроков.","ru")
locList.addLoc("edict_cgm_disable_player_autobuild_desc","Отключает автоматизированное строительство. Возвращает остатки минералов из строительного резерва. Никакого влияния на AI или других игроков.","ru")

locList.addLoc("edict_cgm_disable_sector_ai","Выключить базовый ИИ секторов","ru")
locList.addLoc("edict_cgm_enable_sector_ai","Включить базовый ИИ секторов","ru")
locList.addLoc("edict_cgm_disable_sector_ai_desc","ИИ больше не будет строить новые здания в ваших секторах. Включите автоматическую конструкцию с полным или секторальным построением, чтобы автоматически построить в своих секторах разумным способом. ИИ все равно будет обновляться!","ru")
locList.addLoc("edict_cgm_enable_sector_ai_desc","ИИ снова будет строить новые здания в секторах самостоятельно.","ru")


locList.addLoc("cgm_beta_updated_title","CGM Buildings: Важное обновление","ru")
locList.addLoc("cgm_beta_updated_desc","Мы внедрили новую автоматическую процедуру строительства, как для ИИ, так и для игрока. Это должно привести к умной застройке и закончить глупое распределение ИИ. По умолчанию, в любой стране под контролем ИИ застройка базовым игровым ИИ теперь отключена, и новая процедура активна. В империях игроков новые указы могут использоваться для деактивации для ИИ строительства в секторах или для активации полной или секторальной автоматизированной застройки","ru")
locList.addLoc("cgm_beta_updated_configure_button_name","Изменить настройки по умолчанию","ru")

locList.addLoc("cgm_main_menu_close_desc","Закрыть меню","ru")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_name","Включить здания CGM","ru")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_desc","Эта опция подключает ресурсы модификации CGM. Все стандартные здания из базовой игры, такие как шахты и электростанции, автоматически заменяются и все недостающее технологии автоматически выдаются.\n Обратите внимание, эта опция доступна только в начале игры и не может быть отключена.","ru")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_name","Сохранить здания базовой игры","ru")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_desc","Эта опция сохраняет здания из базовой игры. Существующие здания и технологии остаются без изменений. Выбрав эту опцию, вы получите доступ к дополнительным настройкам.","ru")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_name","Подключить измененные параметры зданий","ru")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_desc","Эта опция подключает переработанные параметры зданий. Изменяет производимые ресурсы, планетарные модификаторы и так далее. Эту опцию можно включать и выключать во время игры на ваше усмотрение.","ru")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_name","Отключить переработанные параметры зданий","ru")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_desc","Эта опция отключает переработанные параметры зданий. Все здания из базовой игры вернутся к изначальным параметрам.","ru")
locList.addLoc("#cgm_ai_enable_vanilla_name","Включить базовое строительство для ИИ","ru")
locList.addLoc("#cgm_ai_enable_vanilla_desc","Базовое строительство для ИИ включено. Это необходимо для прекращения строительства, вызванного модом.","ru")
locList.addLoc("#cgm_ai_disable_vanilla_name","Выключить базовое строительство для ИИ","ru")
locList.addLoc("#cgm_ai_disable_vanilla_desc","Базовый ИИ сможет только модернизировать здания, а не строить новые. Новые постройки будут созданы сценариями (обычные для ресурсов, но с повышенными весами).","ru")
locList.addLoc("#cgm_ai_enable_autobuild_name","Включить расширенные ИИ-скрипты","ru")
locList.addLoc("#cgm_ai_enable_autobuild_desc","ИИ будет строить с использованием расширенных ИИ-скриптов. для прекращения строительства, вызванного базовым ИИ","ru")
locList.addLoc("#cgm_disable_autobuild_name","Выключить расширенные ИИ-скрипты","ru")
locList.addLoc("#cgm_disable_autobuild_desc","ИИ не будет строить с использованием расширенных ИИ-скриптов.","ru")

locList.addLoc("cgm_ai_preset_cgm_ai_routines_name","Новые скрипты для ИИ и автопостройка","ru")
locList.addLoc("cgm_ai_preset_cgm_ai_routines_desc","Эта опция включает скрипты CGM для ИИ и автопостройки. Базовая застройка ИИ отключена, чтобы максимизировать производительность.","ru")
locList.addLoc("cgm_ai_preset_mixed_ai_routines_name","Смешанные скрипты для ИИ и автопостройка","ru")
locList.addLoc("cgm_ai_preset_mixed_ai_routines_desc","Эта опция включает скрипты CGM для ИИ и автопостройки. Базовая застройка ИИ не отключена и ИИ будет строить с использованием увеличенных весов вместе с CGM.","ru")
locList.addLoc("cgm_ai_preset_vanilla_ai_routines_name","Базовая застройка ИИ","ru")
locList.addLoc("cgm_ai_preset_vanilla_ai_routines_desc","Эта опция выключает скрипты CGM для ИИ и автопостройки. Базовая застройка ИИ не отключена и ИИ будет строить с использованием увеличенных весов, но без улучшенных скриптов.","ru")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_name","Продвинутая настройка зданий","ru")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_desc","Эта опция открывает меню продвинутых настроек зданий, где вы сможете изменить стоимость и время постройки зданий конкретных типов.","ru")
locList.addLoc("cgm_main_menu_title","Главное меню CGM","ru")
locList.addLoc("cgm_main_menu_desc","В этом меню вы можете решить играть ли со ресурсодобывающими зданиями из базовой игры или из CGM.\n\nОбратите внимание: если вы подключите контент из CGM, мод сконвертирует уже существующие здания. Это действие необратимо.","ru")
locList.addLoc("cgm_main_menu_header","Core Game Mechanics","ru")
locList.addLoc("cgm_main_menu_close_name","Закрыть меню","ru")

#Allow Stuff

locList.addLoc("requires_non_machine_empire_capital","Требуется §HСтолица империи§!.","ru")
locList.addLoc("requires_building_capital_0","Требуется любая §HПланетарная столица§!.","ru")
locList.addLoc("requires_building_capital_0_or_hab","Требуется любая §Hстолица§!.","ru")
locList.addLoc("requires_building_hab_capital","На этой планете требуется §H$building_hab_capital$§! или §HСтолица империи§!.","ru")
locList.addLoc("requires_building_capital_2_or_hab","Требуется §HПланетарная столица§! или §H$building_hab_capital$§!.","ru")
locList.addLoc("requires_energy_tile","На квадрате должна быть £energy энергия.","ru")
locList.addLoc("requires_minerals_tile","На квадрате должны быть £minerals минералы.","ru")
locList.addLoc("requires_food_tile","На квадрате должна быть £food пища.","ru")
locList.addLoc("requires_engineering_research_tile","На квадрате должны быть £engineering инженерные исследования.","ru")
locList.addLoc("requires_physics_research_tile","На квадрате должны быть £physics физически исследования.","ru")
locList.addLoc("requires_society_research_tile","На квадрате должны быть £society социальные исследования.","ru")
locList.addLoc("requires_megastructure_node_tile","На квадрате должен быть £megastructure_node мегаструктурный узел.","ru")

#Tech

locList.addLoc("tech_biofuel_refining_1_desc","Сложные органические соединения можно превратить в источник дешёвого топлива. Хотя это и менее эффективно, чем синтез радиоактивных изотопов, органические соединения более распространены.","ru")
locList.addLoc("tech_biofuel_refining_1","Базовая очистка биотоплива","ru")
locList.addLoc("tech_biofuel_refining_2_desc","Эффективность нашего биотоплива может быть повышена при помощи генетически модифицированных бактерий, выделяющих псевдо-нефть.","ru")
locList.addLoc("tech_biofuel_refining_2","Улучшенная очистка биотоплива","ru")
locList.addLoc("tech_biofuel_refining_3_desc","Манипулируя органическими соединениями на микроуровне, мы можем синтезировать намного более эффективное искусственное биотопливо.","ru")
locList.addLoc("tech_biofuel_refining_3","Продвинутый синтез биотоплива","ru")
locList.addLoc("tech_biofuel_refining_4_desc","Продвинутые методики синтеза позволяет нам создать твердое биотопливо, что облегчит перевозку конечного продукта и сделает его намного эффективнее.","ru")
locList.addLoc("tech_biofuel_refining_4","Искусственное сгущение биотоплива","ru")
locList.addLoc("tech_biofuel_refining_5_desc","Использование техники в пикометрическом масштабе делает возможным практически безотходное производство биотоплива.","ru")
locList.addLoc("tech_biofuel_refining_5","$optimal$ Синтез биотоплива","ru")
locList.addLoc("tech_power_plant_5_desc","Использование квантового катализа позволит нам производить невероятное количество энергии.","ru")
locList.addLoc("tech_power_plant_5","Квантовый синтез изотопов","ru")
locList.addLoc("tech_mining_network_5_desc","Использование гравитонных дрелей позволяет точно и быстро проникать в глубокие слои.","ru")
locList.addLoc("tech_mining_network_5","Совершенное горное дело","ru")
locList.addLoc("tech_superior_agriculture_desc","Использование наноактивного грунта позволит нам выращивать невероятные объёмы урожая.","ru")
locList.addLoc("tech_superior_agriculture","Совершенное сельское хозяйство","ru")
locList.addLoc("tech_biolab_4_desc","Представив время единым холистическим континуумом, мы сможем рассматривать кажущиеся независимыми феномены как фундаментально связанные.","ru")
locList.addLoc("tech_biolab_4","Холистическая психоистория","ru")
locList.addLoc("tech_physics_lab_4_desc","Теории дошли до отметки, где мы можем начать поискии омега-теории, способной описать не только нашу вселенную, но и другие измерения.","ru")
locList.addLoc("tech_physics_lab_4","Омега-Теория","ru")
locList.addLoc("tech_engineering_lab_4_desc","Наши исследования материалов дошли до отметки позволяющей нам создавать и использовать самоформирующиеся и саморазрабатывающиеся наноматериалы.","ru")
locList.addLoc("tech_engineering_lab_4","Теория умной материи","ru")
locList.addLoc("tech_agricultural_processing_1_desc","Нанотехнологии, изначально разработанные для развития наших космических станций, позволят заметно увеличить урожайность ферм.","ru")
locList.addLoc("tech_agricultural_processing_1","Продвинутая сельскохозяйственная обработка","ru")
locList.addLoc("tech_agricultural_processing_2_desc","Использование продвинутых роботехнологий позволяет нам автоматизировать и улучшить процесс переработки органических материалов в пригодную для употребления пищу.","ru")
locList.addLoc("tech_agricultural_processing_2","Совершенная сельскохозяйственная обработка","ru")
locList.addLoc("tech_hyperstorage_1","Гиперхранилища","ru")
locList.addLoc("tech_hyperstorage_1_desc","Если хранение сформулировать как научную проблему, это обязательно приведет к появлению новой парадигмы.","ru")
locList.addLoc("tech_hyperstorage_2","Продвинутые гиперхранилища","ru")
locList.addLoc("tech_hyperstorage_2_desc","Недавние открытия в области нанометрического хранения могут значительно повысить эффективность наших гиперхранилищ.","ru")
locList.addLoc("tech_hyperstorage_3","Совершенные гиперхранилища","ru")
locList.addLoc("tech_hyperstorage_3_desc","Новые достижения в изучении энтропии позволят ещё сильнее увеличить эффективность гиперхранилищ.","ru")

### Strategic Resources

locList.addLoc("sr_megastructure_node","Мегаструктурный узел","ru")
locList.addLoc("sr_megastructure_node_desc","Мегаструктурный узел представляет собой структурное соединение, где внутренняя матрица энергии мегаструктуры может быть расширена.","ru")


### Modifiers

locList.addLoc("capital_building_build_cost_mult","Цена столичных зданий","ru")
locList.addLoc("capital_building_construction_speed_mult","Скорость строительства столичных зданий","ru")
locList.addLoc("empire_unique_building_build_cost_mult","Цена уникальных для империи зданий","ru")
locList.addLoc("empire_unique_building_construction_speed_mult","Скорость строительства уникальных для империи зданий","ru")
locList.addLoc("planet_unique_building_build_cost_mult","Цена уникальных для планеты зданий","ru")
locList.addLoc("planet_unique_building_construction_speed_mult","Скорость строительства уникальных для планеты зданий","ru")
locList.addLoc("military_building_build_cost_mult","Цена военных зданий","ru")
locList.addLoc("military_building_construction_speed_mult","Скорость строительства военных зданий","ru")
locList.addLoc("standard_resource_building_build_cost_mult","Цена стандартных ресурсопроизводящих зданий","ru")
locList.addLoc("standard_resource_building_construction_speed_mult","Скорость строительства стандартных ресурсопроизводящих зданий","ru")
locList.addLoc("research_resource_building_build_cost_mult","Цена научных зданий","ru")
locList.addLoc("research_resource_building_construction_speed_mult","Скорость строительства научных зданий","ru")
locList.addLoc("unity_resource_building_build_cost_mult","Цена зданий производящих единство","ru")
locList.addLoc("unity_resource_building_construction_speed_mult","Скорость строительства зданий производящих единство","ru")
locList.addLoc("special_resource_building_build_cost_mult","Цена специальных ресурсных зданий","ru")
locList.addLoc("special_resource_building_construction_speed_mult","Скорость строительства специальных ресурсных зданий","ru")
locList.addLoc("replicator_building_build_cost_mult","Цена репликаторов","ru")
locList.addLoc("replicator_building_construction_speed_mult","Скорость строительства репликаторов","ru")
locList.addLoc("static_planet_resource_physics_research_add","Месячные очки физических исследований","ru")
locList.addLoc("static_planet_resource_engineering_research_add","Месячные очки инженерных исследований","ru")
locList.addLoc("static_planet_resource_society_research_add","Месячные очки социологических исследований","ru")

### Triggered Planet Modifiers Keys

locList.addLoc("capital_3_resource_bonus_modifier","Бонус имперской столицы У5","ru")
locList.addLoc("capital_3_resource_bonus_modifier_desc","Это специальный бонус, предоставляемый добывающим зданием 5 уровня планете с имперской столицей.","ru")
locList.addLoc("power_plant_5_regular_capital_modifier","Бонус имперской столицы: Электростанция У5","ru")
locList.addLoc("power_plant_5_ringworld_capital_modifier","Бонус имперской столицы: Электростанция У5 (Мир-кольцо)","ru")
locList.addLoc("mining_network_5_regular_capital_modifier","Бонус имперской столицы: Добывающее предприятие У5","ru")
locList.addLoc("mining_network_5_ringworld_capital_modifier","Бонус имперской столицы: Добывающее предприятие У5 (Мир-кольцо)","ru")
locList.addLoc("hydroponics_farm_5_regular_capital_modifier","Бонус имперской столицы: Гидропонная ферма У5","ru")
locList.addLoc("hydroponics_farm_5_ringworld_capital_modifier","Бонус имперской столицы: Гидропонная ферма У5 (Мир-кольцо)","ru")
locList.addLoc("engineering_facility_4_regular_capital_modifier","Бонус имперской столицы: Инженерный комплекс У5","ru")
locList.addLoc("engineering_facility_4_ringworld_capital_modifier","Бонус имперской столицы: Инженерный комплекс У5 (Мир-кольцо)","ru")
locList.addLoc("physics_lab_4_regular_capital_modifier","Бонус имперской столицы: $physics_lab$ У5","ru")
locList.addLoc("physics_lab_4_ringworld_capital_modifier","Бонус имперской столицы: $physics_lab$ У5 (Мир-кольцо)","ru")
locList.addLoc("biolab_4_regular_capital_modifier","Бонус имперской столицы: Биолаборатория У5","ru")
locList.addLoc("biolab_4_ringworld_capital_modifier","Бонус имперской столицы: Биолаборатория У5 (Мир-кольцо)","ru")

### Building Localisations

locList.addLoc("mining_complex","Добывающий комплекс","ru")
locList.addLoc("mining_complex_desc","Добывающие комплексы - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £minerals минералы.\n\n У них есть базовая выработка ресурсов, который зависит от конкретного уровня здания, а также §H+100%§! к количеству £minerals минералов на клетке, на которой они построены.","ru")
locList.addLoc("farming_complex","Сельскохозяйственный комплекс","ru")
locList.addLoc("farming_complex_desc","Сельскохозяйственные комплексы - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £food пища.\n\n У них есть базовая выработка ресурсов, который зависит от конкретного уровня здания, а также §H+100%§! к количеству £food пищи на клетке, на которой они построены.","ru")
locList.addLoc("isotope_refinery","Изотопный очиститель","ru")
locList.addLoc("isotope_refinery_desc","Изотопные очистители - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £energy энергия.\n\n У них есть базовая выработка ресурсов, который зависит от конкретного уровня здания, а также §H+100%§! к количеству £energy энергии на клетке, на которой они построены.","ru")
locList.addLoc("biofuel_refinery","Биотоливный очиститель","ru")
locList.addLoc("biofuel_refinery_desc","Биотоливные очистители - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £food пища.\n\n У них есть базовая выработка ресурсов, который зависит от конкретного уровня здания, а также §H+100%§! к количеству £food пищи на клетке, на которой они построены, конвентированное в £energy энергию.","ru")
locList.addLoc("society_lab","Биолаборатория","ru")
locList.addLoc("society_lab_desc","Биолаборатории - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £society очки социологических исследований.\n\n У них есть базовая выработка ресурсов, который зависит от конкретного уровня здания, а также §H+100%§! к количеству очков £society социологических исследований на клетке, на которой они построены.","ru")
locList.addLoc("physics_lab","Физическая лаборатория","ru")
locList.addLoc("physics_lab_desc","Физические лаборатории - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £physics очки физических исследований.\n\n У них есть базовая выработка ресурсов, который зависит от конкретного уровня здания, а также §H+100%§! к количеству очков £physics физических исследований на клетке, на которой они построены.","ru")
locList.addLoc("engineering_lab","Инженерный комплекс","ru")
locList.addLoc("engineering_lab_desc","Инженерные комплексs - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £engineering очки инженерных исследований.\n\n TУ них есть базовая выработка ресурсов, который зависит от конкретного уровня здания, а также §H+100%§! к количеству очков £engineering инженерных исследований на клетке, на которой они построены.","ru")
locList.addLoc("energy_matter_converter","Преобразователь энергии","ru")
locList.addLoc("energy_matter_converter_desc","Преобразователи энергии - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £megastructure_node мегаструктурный узел.\n\n У них есть статичная выработка ресурсов, а также §H+3§! к количеству £minerals минералов, но они имеют сильный системный эффект (£minerals), который зависит от количества £megastructure_node мегаструктурных узлов на клетке, на которой они построены, а так же от уровня здания.","ru")
locList.addLoc("energy_conduit","Энергопроводник","ru")
locList.addLoc("energy_conduit_desc","Энергопроводники - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £megastructure_node мегаструктурный узел.\n\n У них есть статичная выработка ресурсов, а также §H+3§! к количеству £energy энергии, но они имеют сильный системный эффект (£energy), который зависит от количества £megastructure_node мегаструктурных узлов на клетке, на которой они построены, а так же от уровня здания.","ru")
locList.addLoc("food_replicator","Репликатор продуктов питания","ru")
locList.addLoc("food_replicator_desc","Репликаторы продуктов питания - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £megastructure_node мегаструктурный узел.\n\n У них есть статичная выработка ресурсов, а также §H+3§! к количеству £food пищу, но они имеют сильный системный эффект (£food), который зависит от количества £megastructure_node мегаструктурных узлов на клетке, на которой они построены, а так же от уровня здания.","ru")
locList.addLoc("computational_array","Вычислительный массив","ru")
locList.addLoc("computational_array_desc","Вычислительные массивы - §Hограниченные по клеткам§! здания, которые могут быть построены только на клетках, где есть £megastructure_node мегаструктурный узел.\n\n У них есть статичная выработка ресурсов, а также §H+1/+1/+1§! к очкам £society социологических, £physics физических и £engineering инженерных исследований, но они имеют сильный системный эффект (£energy), который зависит от количества £megastructure_node мегаструктурных узлов на клетке, на которой они построены, а так же от уровня здания.","ru")
locList.addLoc("economic_district","Экономический район","ru")
locList.addLoc("economic_district_desc","Экономические районы - не ограниченные по клеткам здания, вырабатывающие £energy энергию. Эти здания представляют собой центры торговли и экономического развития.\n\n У них есть как базовая выработка ресурсов, так и статичныий ресурс, который масштабируется от соответствующего уровня здания.","ru")
locList.addLoc("manufacturing_complex","Производственный комплекс","ru")
locList.addLoc("manufacturing_complex_desc","Производственные комплексы - не ограниченные по клеткам здания, вырабатывающие £minerals минералы. Эти здания представляют собой центры промышленного производства и развития.\n\n У них есть как базовая выработка ресурсов, так и статичныий ресурс, который масштабируется от соответствующего уровня здания.","ru")
locList.addLoc("hydroponic_farm","Гидропонное соединение","ru")
locList.addLoc("hydroponic_farm_desc","Гидропонные соединения - не ограниченные по клеткам здания, вырабатывающие £food пищу. Эти здания представляют собой особенно контролируемые самосохраняющиеся биосферы, предназначенные для производства продуктов питания.\n\n У них есть как базовая выработка ресурсов, так и статичныий ресурс, который масштабируется от соответствующего уровня здания.","ru")
locList.addLoc("sociological_campus","Социологический кампус","ru")
locList.addLoc("sociological_campus_desc","Социологические кампусы - не ограниченные по клеткам здания, вырабатывающие £society очки социологических исследований. Эти здания представляют собой центры научных исследований и разработок.\n\n У них есть как базовая выработка ресурсов, так и статичныий ресурс, который масштабируется от соответствующего уровня здания.","ru")
locList.addLoc("physics_campus","Физический кампус","ru")
locList.addLoc("physics_campus_desc","Физические кампусы - не ограниченные по клеткам здания, вырабатывающие £physics очки физических исследований. Эти здания представляют собой центры научных исследований и разработок.\n\n У них есть как базовая выработка ресурсов, так и статичныий ресурс, который масштабируется от соответствующего уровня здания.","ru")
locList.addLoc("engineering_campus","Инженерный кампус","ru")
locList.addLoc("engineering_campus_desc","Инженерные кампусы - не ограниченные по клеткам здания, вырабатывающие £engineering очки инженерных исследований. Эти здания представляют собой центры научных исследований и разработок.\n\n У них есть как базовая выработка ресурсов, так и статичныий ресурс, который масштабируется от соответствующего уровня здания.","ru")
locList.addLoc("agricultural_processor","Сельскохозяйственный перерабатывающий завод","ru")
locList.addLoc("agricultural_processor_desc","Сельскохозяйственные перерабатывающие заводы производят немного £food пищи, но, что более важно, увеличить общее количество выработки £food пищи на планете.","ru")
locList.addLoc("hyperstorage_facility","Hyperstorage Facility","ru")
locList.addLoc("hyperstorage_facility_desc","В гиперхранилищах используются режущие кромки и технологии вакуумного манипулирования для хранения материалов.\n\n В то время как эти здания производят немного £minerals минералов для империй андроидов и £food еды и £minerals минералов для империй органиков, их основное преимущество появляется, когда империя страдает от §Rдефицита минералов§!, §Rдефицита энергии§! или, в случае империй органиков, §Rголода§!. Когда это происходит, гиперхранилище начнет производить большие объемы до 2 §Gтребуемых ресурсов§!.","ru")

### Generic Keys - these are used for the different variations of the buildings
locList.addLoc("cgm_building_mining_complex_1","$mining_complex$ I","ru")
locList.addLoc("cgm_building_mining_complex_1_desc","$basic$ $mining_complex$.\n\n$mining_complex_desc$","ru")
locList.addLoc("cgm_building_mining_complex_2","$mining_complex$ II","ru")
locList.addLoc("cgm_building_mining_complex_2_desc","$improved$ $mining_complex$.\n\n$mining_complex_desc$","ru")
locList.addLoc("cgm_building_mining_complex_3","$mining_complex$ III","ru")
locList.addLoc("cgm_building_mining_complex_3_desc","$enhanced$ $mining_complex$.\n\n$mining_complex_desc$","ru")
locList.addLoc("cgm_building_mining_complex_4","$mining_complex$ IV","ru")
locList.addLoc("cgm_building_mining_complex_4_desc","$advanced$ $mining_complex$.\n\n$mining_complex_desc$","ru")
locList.addLoc("cgm_building_mining_complex_5","$mining_complex$ V","ru")
locList.addLoc("cgm_building_mining_complex_5_desc","$superior$ $mining_complex$.\n\n$mining_complex_desc$","ru")
locList.addLoc("cgm_building_farming_complex_1","$farming_complex$ I","ru")
locList.addLoc("cgm_building_farming_complex_1_desc","$basic$ $farming_complex$.\n\n$farming_complex_desc$","ru")
locList.addLoc("cgm_building_farming_complex_2","$farming_complex$ II","ru")
locList.addLoc("cgm_building_farming_complex_2_desc","$improved$ $farming_complex$.\n\n$farming_complex_desc$","ru")
locList.addLoc("cgm_building_farming_complex_3","$farming_complex$ III","ru")
locList.addLoc("cgm_building_farming_complex_3_desc","$enhanced$ $farming_complex$.\n\n$farming_complex_desc$","ru")
locList.addLoc("cgm_building_farming_complex_4","$farming_complex$ IV","ru")
locList.addLoc("cgm_building_farming_complex_4_desc","$advanced$ $farming_complex$.\n\n$farming_complex_desc$","ru")
locList.addLoc("cgm_building_farming_complex_5","$farming_complex$ V","ru")
locList.addLoc("cgm_building_farming_complex_5_desc","$superior$ $farming_complex$.\n\n$farming_complex_desc$","ru")
locList.addLoc("cgm_building_isotope_refinery_1","$isotope_refinery$ I","ru")
locList.addLoc("cgm_building_isotope_refinery_1_desc","$basic$ $isotope_refinery$.\n\n$isotope_refinery_desc$","ru")
locList.addLoc("cgm_building_isotope_refinery_2","$isotope_refinery$ II","ru")
locList.addLoc("cgm_building_isotope_refinery_2_desc","$improved$ $isotope_refinery$.\n\n$isotope_refinery_desc$","ru")
locList.addLoc("cgm_building_isotope_refinery_3","$isotope_refinery$ III","ru")
locList.addLoc("cgm_building_isotope_refinery_3_desc","$enhanced$ $isotope_refinery$.\n\n$isotope_refinery_desc$","ru")
locList.addLoc("cgm_building_isotope_refinery_4","$isotope_refinery$ IV","ru")
locList.addLoc("cgm_building_isotope_refinery_4_desc","$advanced$ $isotope_refinery$.\n\n$isotope_refinery_desc$","ru")
locList.addLoc("cgm_building_isotope_refinery_5","$isotope_refinery$ V","ru")
locList.addLoc("cgm_building_isotope_refinery_5_desc","$superior$ $isotope_refinery$.\n\n$isotope_refinery_desc$","ru")
locList.addLoc("cgm_building_biofuel_refinery_1","$biofuel_refinery$ I","ru")
locList.addLoc("cgm_building_biofuel_refinery_1_desc","$basic$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","ru")
locList.addLoc("cgm_building_biofuel_refinery_2","$biofuel_refinery$ II","ru")
locList.addLoc("cgm_building_biofuel_refinery_2_desc","$improved$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","ru")
locList.addLoc("cgm_building_biofuel_refinery_3","$biofuel_refinery$ III","ru")
locList.addLoc("cgm_building_biofuel_refinery_3_desc","$enhanced$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","ru")
locList.addLoc("cgm_building_biofuel_refinery_4","$biofuel_refinery$ IV","ru")
locList.addLoc("cgm_building_biofuel_refinery_4_desc","$advanced$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","ru")
locList.addLoc("cgm_building_biofuel_refinery_5","$biofuel_refinery$ V","ru")
locList.addLoc("cgm_building_biofuel_refinery_5_desc","$superior$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","ru")
locList.addLoc("cgm_building_society_lab_1","$society_lab$ I","ru")
locList.addLoc("cgm_building_society_lab_1_desc","$basic$ $society_lab$.\n\n$society_lab_desc$","ru")
locList.addLoc("cgm_building_society_lab_2","$society_lab$ II","ru")
locList.addLoc("cgm_building_society_lab_2_desc","$improved$ $society_lab$.\n\n$society_lab_desc$","ru")
locList.addLoc("cgm_building_society_lab_3","$society_lab$ III","ru")
locList.addLoc("cgm_building_society_lab_3_desc","$enhanced$ $society_lab$.\n\n$society_lab_desc$","ru")
locList.addLoc("cgm_building_society_lab_4","$society_lab$ IV","ru")
locList.addLoc("cgm_building_society_lab_4_desc","$advanced$ $society_lab$.\n\n$society_lab_desc$","ru")
locList.addLoc("cgm_building_society_lab_5","$society_lab$ V","ru")
locList.addLoc("cgm_building_society_lab_5_desc","$superior$ $society_lab$.\n\n$society_lab_desc$","ru")
locList.addLoc("cgm_building_physics_lab_1","$physics_lab$ I","ru")
locList.addLoc("cgm_building_physics_lab_1_desc","$basic$ $physics_lab$.\n\n$physics_lab_desc$","ru")
locList.addLoc("cgm_building_physics_lab_2","$physics_lab$ II","ru")
locList.addLoc("cgm_building_physics_lab_2_desc","$improved$ $physics_lab$.\n\n$physics_lab_desc$","ru")
locList.addLoc("cgm_building_physics_lab_3","$physics_lab$ III","ru")
locList.addLoc("cgm_building_physics_lab_3_desc","$enhanced$ $physics_lab$.\n\n$physics_lab_desc$","ru")
locList.addLoc("cgm_building_physics_lab_4","$physics_lab$ IV","ru")
locList.addLoc("cgm_building_physics_lab_4_desc","$advanced$ $physics_lab$.\n\n$physics_lab_desc$","ru")
locList.addLoc("cgm_building_physics_lab_5","$physics_lab$ V","ru")
locList.addLoc("cgm_building_physics_lab_5_desc","$superior$ $physics_lab$.\n\n$physics_lab_desc$","ru")
locList.addLoc("cgm_building_engineering_lab_1","$engineering_lab$ I","ru")
locList.addLoc("cgm_building_engineering_lab_1_desc","$basic$ $engineering_lab$.\n\n$engineering_lab_desc$","ru")
locList.addLoc("cgm_building_engineering_lab_2","$engineering_lab$ II","ru")
locList.addLoc("cgm_building_engineering_lab_2_desc","$improved$ $engineering_lab$.\n\n$engineering_lab_desc$","ru")
locList.addLoc("cgm_building_engineering_lab_3","$engineering_lab$ III","ru")
locList.addLoc("cgm_building_engineering_lab_3_desc","$enhanced$ $engineering_lab$.\n\n$engineering_lab_desc$","ru")
locList.addLoc("cgm_building_engineering_lab_4","$engineering_lab$ IV","ru")
locList.addLoc("cgm_building_engineering_lab_4_desc","$advanced$ $engineering_lab$.\n\n$engineering_lab_desc$","ru")
locList.addLoc("cgm_building_engineering_lab_5","$engineering_lab$ V","ru")
locList.addLoc("cgm_building_engineering_lab_5_desc","$superior$ $engineering_lab$.\n\n$engineering_lab_desc$","ru")
locList.addLoc("cgm_building_energy_matter_converter_1","$energy_matter_converter$ I","ru")
locList.addLoc("cgm_building_energy_matter_converter_1_desc","$basic$ $energy_matter_converter$.\n\n$energy_matter_converter_desc$","ru")
locList.addLoc("cgm_building_energy_matter_converter_2","$energy_matter_converter$ II","ru")
locList.addLoc("cgm_building_energy_matter_converter_2_desc","$improved$ $energy_matter_converter$.\n\n$energy_matter_converter_desc$","ru")
locList.addLoc("cgm_building_energy_matter_converter_3","$energy_matter_converter$ III","ru")
locList.addLoc("cgm_building_energy_matter_converter_3_desc","$enhanced$ $energy_matter_converter$.\n\n$energy_matter_converter_desc$","ru")
locList.addLoc("cgm_building_energy_conduit_1","$energy_conduit$ I","ru")
locList.addLoc("cgm_building_energy_conduit_1_desc","$basic$ $energy_conduit$.\n\n$energy_conduit_desc$","ru")
locList.addLoc("cgm_building_energy_conduit_2","$energy_conduit$ II","ru")
locList.addLoc("cgm_building_energy_conduit_2_desc","$improved$ $energy_conduit$.\n\n$energy_conduit_desc$","ru")
locList.addLoc("cgm_building_energy_conduit_3","$energy_conduit$ III","ru")
locList.addLoc("cgm_building_energy_conduit_3_desc","$enhanced$ $energy_conduit$.\n\n$energy_conduit_desc$","ru")
locList.addLoc("cgm_building_food_replicator_1","$food_replicator$ I","ru")
locList.addLoc("cgm_building_food_replicator_1_desc","$basic$ $food_replicator$.\n\n$food_replicator_desc$","ru")
locList.addLoc("cgm_building_food_replicator_2","$food_replicator$ II","ru")
locList.addLoc("cgm_building_food_replicator_2_desc","$improved$ $food_replicator$.\n\n$food_replicator_desc$","ru")
locList.addLoc("cgm_building_food_replicator_3","$food_replicator$ III","ru")
locList.addLoc("cgm_building_food_replicator_3_desc","$enhanced$ $food_replicator$.\n\n$food_replicator_desc$","ru")
locList.addLoc("cgm_building_computational_array_1","$computational_array$ I","ru")
locList.addLoc("cgm_building_computational_array_1_desc","$basic$ $computational_array$.\n\n$computational_array_desc$","ru")
locList.addLoc("cgm_building_computational_array_2","$computational_array$ II","ru")
locList.addLoc("cgm_building_computational_array_2_desc","$improved$ $computational_array$.\n\n$computational_array_desc$","ru")
locList.addLoc("cgm_building_computational_array_3","$computational_array$ III","ru")
locList.addLoc("cgm_building_computational_array_3_desc","$enhanced$ $computational_array$.\n\n$computational_array_desc$","ru")

#### Building Localisations
locList.addLoc("building_economic_district_1","$economic_district$ I","ru")
locList.addLoc("building_economic_district_1_desc","$basic$ $economic_district$.\n\n$economic_district_desc$","ru")
locList.addLoc("building_economic_district_2","$economic_district$ II","ru")
locList.addLoc("building_economic_district_2_desc","$improved$ $economic_district$.\n\n$economic_district_desc$","ru")
locList.addLoc("building_economic_district_3","$economic_district$ III","ru")
locList.addLoc("building_economic_district_3_desc","$enhanced$ $economic_district$.\n\n$economic_district_desc$","ru")
locList.addLoc("building_economic_district_4","$economic_district$ IV","ru")
locList.addLoc("building_economic_district_4_desc","$advanced$ $economic_district$.\n\n$economic_district_desc$","ru")
locList.addLoc("building_economic_district_5","$economic_district$ V","ru")
locList.addLoc("building_economic_district_5_desc","$superior$ $economic_district$.\n\n$economic_district_desc$","ru")
locList.addLoc("building_manufacturing_complex_1","$manufacturing_complex$ I","ru")
locList.addLoc("building_manufacturing_complex_1_desc","$basic$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","ru")
locList.addLoc("building_manufacturing_complex_2","$manufacturing_complex$ II","ru")
locList.addLoc("building_manufacturing_complex_2_desc","$improved$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","ru")
locList.addLoc("building_manufacturing_complex_3","$manufacturing_complex$ III","ru")
locList.addLoc("building_manufacturing_complex_3_desc","$enhanced$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","ru")
locList.addLoc("building_manufacturing_complex_4","$manufacturing_complex$ IV","ru")
locList.addLoc("building_manufacturing_complex_4_desc","$advanced$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","ru")
locList.addLoc("building_manufacturing_complex_5","$manufacturing_complex$ V","ru")
locList.addLoc("building_manufacturing_complex_5_desc","$superior$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","ru")
locList.addLoc("building_hydroponic_farm_1","$hydroponic_farm$ I","ru")
locList.addLoc("building_hydroponic_farm_1_desc","$basic$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","ru")
locList.addLoc("building_hydroponic_farm_2","$hydroponic_farm$ II","ru")
locList.addLoc("building_hydroponic_farm_2_desc","$improved$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","ru")
locList.addLoc("building_hydroponic_farm_3","$hydroponic_farm$ III","ru")
locList.addLoc("building_hydroponic_farm_3_desc","$enhanced$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","ru")
locList.addLoc("building_hydroponic_farm_4","$hydroponic_farm$ IV","ru")
locList.addLoc("building_hydroponic_farm_4_desc","$advanced$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","ru")
locList.addLoc("building_hydroponic_farm_5","$hydroponic_farm$ V","ru")
locList.addLoc("building_hydroponic_farm_5_desc","$superior$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","ru")
locList.addLoc("building_sociological_campus_1","$sociological_campus$ I","ru")
locList.addLoc("building_sociological_campus_1_desc","$basic$ $sociological_campus$.\n\n$sociological_campus_desc$","ru")
locList.addLoc("building_sociological_campus_2","$sociological_campus$ II","ru")
locList.addLoc("building_sociological_campus_2_desc","$improved$ $sociological_campus$.\n\n$sociological_campus_desc$","ru")
locList.addLoc("building_sociological_campus_3","$sociological_campus$ III","ru")
locList.addLoc("building_sociological_campus_3_desc","$enhanced$ $sociological_campus$.\n\n$sociological_campus_desc$","ru")
locList.addLoc("building_sociological_campus_4","$sociological_campus$ IV","ru")
locList.addLoc("building_sociological_campus_4_desc","$advanced$ $sociological_campus$.\n\n$sociological_campus_desc$","ru")
locList.addLoc("building_sociological_campus_5","$sociological_campus$ V","ru")
locList.addLoc("building_sociological_campus_5_desc","$superior$ $sociological_campus$.\n\n$sociological_campus_desc$","ru")
locList.addLoc("building_physics_campus_1","$physics_campus$ I","ru")
locList.addLoc("building_physics_campus_1_desc","$basic$ $physics_campus$.\n\n$physics_campus_desc$","ru")
locList.addLoc("building_physics_campus_2","$physics_campus$ II","ru")
locList.addLoc("building_physics_campus_2_desc","$improved$ $physics_campus$.\n\n$physics_campus_desc$","ru")
locList.addLoc("building_physics_campus_3","$physics_campus$ III","ru")
locList.addLoc("building_physics_campus_3_desc","$enhanced$ $physics_campus$.\n\n$physics_campus_desc$","ru")
locList.addLoc("building_physics_campus_4","$physics_campus$ IV","ru")
locList.addLoc("building_physics_campus_4_desc","$advanced$ $physics_campus$.\n\n$physics_campus_desc$","ru")
locList.addLoc("building_physics_campus_5","$physics_campus$ V","ru")
locList.addLoc("building_physics_campus_5_desc","$superior$ $physics_campus$.\n\n$physics_campus_desc$","ru")
locList.addLoc("building_engineering_campus_1","$engineering_campus$ I","ru")
locList.addLoc("building_engineering_campus_1_desc","$basic$ $engineering_campus$.\n\n$engineering_campus_desc$","ru")
locList.addLoc("building_engineering_campus_2","$engineering_campus$ II","ru")
locList.addLoc("building_engineering_campus_2_desc","$improved$ $engineering_campus$.\n\n$engineering_campus_desc$","ru")
locList.addLoc("building_engineering_campus_3","$engineering_campus$ III","ru")
locList.addLoc("building_engineering_campus_3_desc","$enhanced$ $engineering_campus$.\n\n$engineering_campus_desc$","ru")
locList.addLoc("building_engineering_campus_4","$engineering_campus$ IV","ru")
locList.addLoc("building_engineering_campus_4_desc","$advanced$ $engineering_campus$.\n\n$engineering_campus_desc$","ru")
locList.addLoc("building_engineering_campus_5","$engineering_campus$ V","ru")
locList.addLoc("building_engineering_campus_5_desc","$superior$ $engineering_campus$.\n\n$engineering_campus_desc$","ru")
locList.addLoc("building_agricultural_processor_1","$agricultural_processor$ I","ru")
locList.addLoc("building_agricultural_processor_2","$agricultural_processor$ II","ru")
locList.addLoc("building_hyperstorage_facility_1","$hyperstorage_facility$ I","ru")
locList.addLoc("building_hyperstorage_facility_2","$hyperstorage_facility$ II","ru")
locList.addLoc("building_hyperstorage_facility_3","$hyperstorage_facility$ III","ru")

##### buildings that use a key for localisations

# Debug Resource - these can be turned on to expose the AI logic

locList.addLoc("sr_null_e_desc","REPLACE_ME","ru")
locList.addLoc("sr_null_e","Клетка энергетического здания","ru")
locList.addLoc("sr_null_en_desc","REPLACE_ME","ru")
locList.addLoc("sr_null_en","Клетка инженерного здания","ru")
locList.addLoc("sr_null_f_desc","REPLACE_ME","ru")
locList.addLoc("sr_null_f","Клетка пищевого здания","ru")
locList.addLoc("sr_null_m_desc","REPLACE_ME","ru")
locList.addLoc("sr_null_m","Клетка минерального здания","ru")
locList.addLoc("sr_null_py_desc","REPLACE_ME","ru")
locList.addLoc("sr_null_py","Клетка физического здания","ru")
locList.addLoc("sr_null_sc_desc","REPLACE_ME","ru")
locList.addLoc("sr_null_sc","Клетка социологического здания","ru")
locList.addLoc("sr_null_u_desc","REPLACE_ME","ru")
locList.addLoc("sr_null_u","Клетка здания единства","ru")

### Deposits - these do not actually require a localisation. The localisations below are just placeholder to remove error messages in CWTools

locList.addLoc("1_energy","REPLACE_ME","ru")
locList.addLoc("1_minerals","REPLACE_ME","ru")
locList.addLoc("1_food","REPLACE_ME","ru")
locList.addLoc("1_unity","REPLACE_ME","ru")
locList.addLoc("1_society_research","REPLACE_ME","ru")
locList.addLoc("1_physics_research","REPLACE_ME","ru")
locList.addLoc("1_mining_station_energy","REPLACE_ME","ru")
locList.addLoc("1_mining_station_minerals","REPLACE_ME","ru")
locList.addLoc("1_mining_station_food","REPLACE_ME","ru")
locList.addLoc("1_mining_station_unity","REPLACE_ME","ru")
locList.addLoc("1_mining_station_society_research","REPLACE_ME","ru")
locList.addLoc("1_mining_station_physics_research","REPLACE_ME","ru")
locList.addLoc("1_mining_station_engineering_research","REPLACE_ME","ru")
locList.addLoc("1_research_station_energy","REPLACE_ME","ru")
locList.addLoc("1_research_station_minerals","REPLACE_ME","ru")
locList.addLoc("1_research_station_food","REPLACE_ME","ru")
locList.addLoc("1_research_station_unity","REPLACE_ME","ru")
locList.addLoc("1_research_station_society_research","REPLACE_ME","ru")
locList.addLoc("1_research_station_physics_research","REPLACE_ME","ru")
locList.addLoc("1_research_station_engineering_research","REPLACE_ME","ru")
locList.addLoc("energy_building_tile","REPLACE_ME","ru")
locList.addLoc("minerals_building_tile","REPLACE_ME","ru")
locList.addLoc("food_building_tile","REPLACE_ME","ru")
locList.addLoc("unity_building_tile","REPLACE_ME","ru")
locList.addLoc("society_research_building_tile","REPLACE_ME","ru")
locList.addLoc("engineering_research_building_tile","REPLACE_ME","ru")
locList.addLoc("physics_research_building_tile","REPLACE_ME","ru")
locList.addLoc("special_resource_tile","REPLACE_ME","ru")
locList.addLoc("d_megastructure_node","REPLACE_ME","ru")
