
### Menu Options
locList.addLoc("basic","Базовый","ru")
locList.addLoc("improved","Улучшенный","ru")
locList.addLoc("enhanced","Расширенный","ru")
locList.addLoc("advanced","Продвинутый","ru")
locList.addLoc("Superior","Максимально Равитой","ru")
locList.addLoc("optimal","Оптимальный","ru")

locList.addLoc("edict_cgm_menu_edict_desc","Этот указ открывает главное меню CGM.","ru")
locList.addLoc("edict_cgm_menu_edict","Открыть Меню CGM","ru")
locList.addLoc("cgm_buildings_text","Core Game Mechanics: Здания","ru")
locList.addLoc("cgm_main_menu_close_desc","Закрыть меню","ru")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_name","Включить здания CGM","ru")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_desc","Эта опция подключает модификации ресурсов CGM. Все стандартные здания из базовой игры, такие как шахты и электростанции, автоматически заменяются и все недостающее технологии автоматически выдаются.\n Обратите внимание, эта опция доступна только в начале игры и не может быть отключена.","ru")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_name","Сохранить здания базовой игры","ru")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_desc","Эта опция сохраняет здания из базовой игры. Существующие здания и технологии остаются без изменений. Выбрав эту опцию, вы получите доступ к дополнительным настройкам.","ru")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_name","Подключить измененные параметры зданий","ru")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_desc","Эта опция подключает переработанные параметры зданий. Изменяет производимые ресурсы, планетарные модификаторы и так далее. Эту опцию можно включать и выключать во время игры на ваше усмотрение.","ru")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_name","Отключить переработанные параметры зданий","ru")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_desc","Эта опция отключает переработанные параметры зданий. Все здания из базовой игры вернутся к изначальным параметрам.","ru")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_name","Продвинутая настройка зданий","ru")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_desc","Эта опция открывает меню продвинутых настроек зданий, где вы сможете изменить стоимость и время постройки зданий конкретных типов.","ru")
locList.addLoc("cgm_main_menu_title","Главное меню CGM","ru")
locList.addLoc("cgm_main_menu_desc","В этом меню вы можете решить играть ли со ресурсодобывающими зданиями из базовой игры или из CGM.\n\nОбратите внимание: если вы подключите контент из CGM, мод конвертирует уже существующие здания. Это действие необратимо.","ru")
locList.addLoc("cgm_main_menu_header","Core Game Mechanics","ru")
locList.addLoc("cgm_main_menu_close_name","Закрыть меню","ru")

#Allow Stuff

locList.addLoc("requires_non_machine_empire_capital","На этой планете требуется $building_capital_3$.","ru")
locList.addLoc("requires_building_capital_0","На этой планете требуется любая сталица.","ru")
locList.addLoc("requires_building_capital_0_or_hab","На этой планете требуется любая столица.","ru")
locList.addLoc("requires_building_hab_capital","На этой планете требуется столица империи или столица орбитальной среды обитания.","ru")
locList.addLoc("requires_building_capital_2_or_hab","Требуется столица орбитальной среды обитания.","ru")
locList.addLoc("requires_energy_tile","На квадрате должна быть £energy энергия.","ru")
locList.addLoc("requires_minerals_tile","На квадрате должны быть £minerals минералы.","ru")
locList.addLoc("requires_food_tile","На квадрате должна быть £food еда.","ru")
locList.addLoc("requires_engineering_research_tile","На квадрате должны быть £engineering инженерные исследования.","ru")
locList.addLoc("requires_physics_research_tile","На квадрате должны быть £physics физически исследования.","ru")
locList.addLoc("requires_society_research_tile","На квадрате должны быть £society социальные исследования.","ru")
locList.addLoc("requires_megastructure_node_tile","На квадрате должен быть £megastructure_node мегаструктурный узел.","ru")

locList.addLoc("tech_biofuel_refining_1_desc","Сложные органические соединения можно превратить в источник дешёвого топлива. Хотя это и менее эффективно чем синтез радиоактивных изотопов, органические соединения более распространены.","ru")
locList.addLoc("tech_biofuel_refining_1","Базовая Очистка Биотоплива","ru")
locList.addLoc("tech_biofuel_refining_2_desc","Эффективность нашего биотоплива может быть повышена при помощи генетически модифицированных бактерий, выделяющих псевдо-нефть.","ru")
locList.addLoc("tech_biofuel_refining_2","Улучшенная Очистка Биотоплива","ru")
locList.addLoc("tech_biofuel_refining_3_desc","Манипулируя органическими соединениями на микроуровне, мы можем синтезировать намного более эффективное искусственное биотопливо.","ru")
locList.addLoc("tech_biofuel_refining_3","Продвинутый Синтез Биотоплива","ru")
locList.addLoc("tech_biofuel_refining_4_desc","Продвинутые методики синтеза позволяет нам создать твердое биотопливо, что облегчит перевозку конечного продукта и сделает его намного эффективнее.","ru")
locList.addLoc("tech_biofuel_refining_4","Искусственное Сгущение Биотоплива","ru")
locList.addLoc("tech_biofuel_refining_5_desc","Использование техники в пикометрическом масштабе делает возможным практически безотходное производство биотоплива.","ru")
locList.addLoc("tech_biofuel_refining_5","$optimal$ Синтез Биотоплива","ru")
locList.addLoc("tech_power_plant_5_desc","Использование квантового катализа позволит нам производить невероятное количество энергии.","ru")
locList.addLoc("tech_power_plant_5","Квантовый Синтез Изотопов","ru")
locList.addLoc("tech_mining_network_5_desc","Использование гравитонных дрелей позволяет точно и быстро проникать в глубокие слои.","ru")
locList.addLoc("tech_mining_network_5","Максимально Развитое Горное Дело","ru")
locList.addLoc("tech_superior_agriculture_desc","Использование наноактивного грунта позволит нам выращивать невероятные объёмы урожая.","ru")
locList.addLoc("tech_superior_agriculture","Максимально Развитое Сельское Хозяйство","ru")
locList.addLoc("tech_biolab_4_desc","Представив время единым холистическим континуумом, мы сможем рассматривать кажущиеся независимыми феномены как фундаментально связанные.","ru")
locList.addLoc("tech_biolab_4","Холистическая Психоистория","ru")
locList.addLoc("tech_physics_lab_4_desc","Теории дошли до отметки, где мы можем начать поискии омега-теории, способной описать не только нашу вселенную, но и другие измерения.","ru")
locList.addLoc("tech_physics_lab_4","Омега-Теория","ru")
locList.addLoc("tech_engineering_lab_4_desc","Наши исследования материалов дошли до отметки позволяющей нам создавать и использовать самоформирующиеся и саморазрабатывающиеся наноматериалы.","ru")
locList.addLoc("tech_engineering_lab_4","Теория Умной Материи","ru")
locList.addLoc("tech_agricultural_processing_1_desc","Нанотехнологии, изначально разработанные для развития наших космических станций, позволяют заметно увеличить урожайность ферм.","ru")
locList.addLoc("tech_agricultural_processing_1","Продвинутая Сельскохозяйственная Обработка","ru")
locList.addLoc("tech_agricultural_processing_2_desc","Использование продвинутых роботехнологий позволяет дальнейшую автоматизацию и развитие переработки органических материалов в пригодную для употребления пищу.","ru")
locList.addLoc("tech_agricultural_processing_2","Максимально Развитая Сельскохозяйственная Обработка","ru")
locList.addLoc("tech_hyperstorage_1","Гиперхранилища","ru")
locList.addLoc("tech_hyperstorage_1_desc","Хранение поднимает научные вопросы, которые ведут к новым парадигмам.","ru")
locList.addLoc("tech_hyperstorage_2","Продвинутые Гиперхранилища","ru")
locList.addLoc("tech_hyperstorage_2_desc","Недавние открытия в области нанометрического хранения могут значительно повысить эффективность наших гиперхранилищ.","ru")
locList.addLoc("tech_hyperstorage_3","Максимально Развитые Гиперхранилища","ru")
locList.addLoc("tech_hyperstorage_3_desc","Новые достижения в изучении энтропии позволят ещё сильнее увеличить эффективность гиперхранилищ.","ru")

### Strategic Resources

locList.addLoc("sr_megastructure_node","Мегаструктурный Узел","ru")
locList.addLoc("sr_megastructure_node_desc","Мегаструктурный узел представляет собой место, где энергетические системы мегаструктуры могут быть расширены.","ru")


### Modifiers

locList.addLoc("capital_building_build_cost_mult","Цена Столичных Зданий","ru")
locList.addLoc("capital_building_construction_speed_mult","Скорость Строительства Столичных Зданий","ru")
locList.addLoc("empire_unique_building_build_cost_mult","Цена Уникальных для Империи Зданий","ru")
locList.addLoc("empire_unique_building_construction_speed_mult","Скорость Строительства Уникальных для Империи Зданий","ru")
locList.addLoc("planet_unique_building_build_cost_mult","Цена Уникальных для Планеты Зданий","ru")
locList.addLoc("planet_unique_building_construction_speed_mult","Скорость Строительства Уникальных для Планеты Зданий","ru")
locList.addLoc("military_building_build_cost_mult","Цена Военных Зданий","ru")
locList.addLoc("military_building_construction_speed_mult","Скорость Строительства Военных Зданий","ru")
locList.addLoc("standard_resource_building_build_cost_mult","Цена Стандартных Ресурсопроизводящих Зданий","ru")
locList.addLoc("standard_resource_building_construction_speed_mult","Скорость Строительства Стандартных Ресурсопроизводящих Зданий","ru")
locList.addLoc("research_resource_building_build_cost_mult","Цена Научных Зданий","ru")
locList.addLoc("research_resource_building_construction_speed_mult","Скорость Строительства Научных Зданий","ru")
locList.addLoc("unity_resource_building_build_cost_mult","Цена Зданий Производящих Единство","ru")
locList.addLoc("unity_resource_building_construction_speed_mult","Скорость Строительства Зданий Производящих Единство","ru")
locList.addLoc("special_resource_building_build_cost_mult","Цена Специальных Ресурсных Зданий","ru")
locList.addLoc("special_resource_building_construction_speed_mult","Скорость Строительства Специальных Ресурсных Зданий","ru")
locList.addLoc("replicator_building_build_cost_mult","Цена Репликаторов","ru")
locList.addLoc("replicator_building_construction_speed_mult","Скорость Строительства Репликаторов","ru")