
### Menu Options
locList.addLoc("basic","Basic","en")
locList.addLoc("improved","Improved","en")
locList.addLoc("enhanced","Enhanced","en")
locList.addLoc("advanced","Advanced","en")
locList.addLoc("Superior","Superior","en")
locList.addLoc("optimal","Optimal","en")

locList.addLoc("edict_cgm_menu_edict_desc","This edict opens the CGM main menu.","en")
locList.addLoc("edict_cgm_menu_edict","Open CGM Menu","en")
locList.addLoc("cgm_buildings_text","Core Game Mechanics: Buildings","en")
locList.addLoc("cgm_main_menu_close_desc","Close Menu","en")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_name","Enable CGM Building Content","en")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_desc","This option enables the CGM resource building rework. All the standard vanilla resource buildings, e.g. mining network or power plants, are automatically replaced and any required technology that is missing is automatically given.\n Please note, this option is only available during Game Start and it cannot be undone.","en")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_name","Keep Vanilla Building Content","en")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_desc","This option sets the game to use the vanilla resource buildings. No changes occur to existing buildings or technologies. Picking this option will unlock further configuration options.","en")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_name","Enable Overhauled Building Stats","en")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_desc","This option enables overhauled building stats. With some buildings having a different resource outputs, planet modifiers etc. from vanilla. This option can be turned on/off at your discretion at any time during the game.","en")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_name","Disable Overhauled Building Stats","en")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_desc","This option disables the overhauled buildings stats. All vanilla content building will have the same stats as in vanilla.","en")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_name","$advanced$ Building Configuration","en")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_desc","This option opens the $advanced$ Building Configuration menu, which allows you to changes the building cost and building time of specific building categories.","en")
locList.addLoc("cgm_main_menu_title","CGM Main Menu","en")
locList.addLoc("cgm_main_menu_desc","In this menu you can choose whether you'd like to play using the vanilla resource buildings or the CGM resource buildings.\n\nPlease note: if you enable CGM game content the mod will auto-convert existing vanilla buildings to the CGM new content. This cannot be undone.","en")
locList.addLoc("cgm_main_menu_header","Core Game Mechanics","en")
locList.addLoc("cgm_main_menu_close_name","Close Menu","en")

#Allow Stuff

locList.addLoc("requires_non_machine_empire_capital","Requires empire capital building.","en")
locList.addLoc("requires_building_capital_0","Requires any planetary capital building.","en")
locList.addLoc("requires_building_capital_0_or_hab","Requires any capital building.","en")
locList.addLoc("requires_building_hab_capital","Requires any habitat capital building or empire capital building.","en")
locList.addLoc("requires_building_capital_2_or_hab","Requires any habitat capital building.","en")
locList.addLoc("requires_energy_tile","Requires Energy £energy on the tile.","en")
locList.addLoc("requires_minerals_tile","Requires Minerals £minerals on the tile.","en")
locList.addLoc("requires_food_tile","Requires Food £food on the tile.","en")
locList.addLoc("requires_engineering_research_tile","Requires Engineering £engineering on the tile.","en")
locList.addLoc("requires_physics_research_tile","Requires Physics £physics on the tile.","en")
locList.addLoc("requires_society_research_tile","Requires Society £society on the tile.","en")
locList.addLoc("requires_megastructure_node_tile","Requires Megastructure Node £megastructure_node on the tile.","en")

locList.addLoc("tech_biofuel_refining_1_desc","Complex organic matter can be converted into a cheap fuel source. Although not as efficient as radio-active isotope synthesis, organic matter is significantly more common.","en")
locList.addLoc("tech_biofuel_refining_1","$basic$ Biofuel Refining","en")
locList.addLoc("tech_biofuel_refining_2_desc","The potency of our biofuel can be $enhanced$ using genetically engineered bacteria that secrets a potent pseudo-oil.","en")
locList.addLoc("tech_biofuel_refining_2","$enhanced$ Biofuel Refining","en")
locList.addLoc("tech_biofuel_refining_3_desc","By manipulating organic molecules on a minute scale, we are able to create significantly more potent artificial biofuel.","en")
locList.addLoc("tech_biofuel_refining_3","$advanced$ Biofuel Synthesis","en")
locList.addLoc("tech_biofuel_refining_4_desc","New synthesis methods allow us to create solid-state biofuel, which makes the end product both more transportable and significantly more potent.","en")
locList.addLoc("tech_biofuel_refining_4","Artifical Biofuel Condensation","en")
locList.addLoc("tech_biofuel_refining_5_desc","The use of picometric scale machinery allows us to synthesize biofuel with almost no waste.","en")
locList.addLoc("tech_biofuel_refining_5","$optimal$ Biofuel Synthesis","en")
locList.addLoc("tech_power_plant_5_desc","The use of quantum catalysis allows us to generate immense amounts of energy.","en")
locList.addLoc("tech_power_plant_5","Quantum Isotope Synthesis","en")
locList.addLoc("tech_mining_network_5_desc","The use of gravitonic drills allows us to precisely and quickly penetrate deep strata.","en")
locList.addLoc("tech_mining_network_5","$superior$ Mining","en")
locList.addLoc("tech_superior_agriculture_desc","The use of nanoactive soil allows us to grow an incredible amount of crops.","en")
locList.addLoc("tech_superior_agriculture","$superior$ Agriculture","en")
locList.addLoc("tech_biolab_4_desc","Regarding temporality as a single holistic continuum allows us to treat seemingly disparate phenomena as fundamentally interconnected.","en")
locList.addLoc("tech_biolab_4","Holistic Psycho-History","en")
locList.addLoc("tech_physics_lab_4_desc","Theory has reached the point where we can begin searching for the omega theory, which is capable of describing not only our universe but other dimensions as well.","en")
locList.addLoc("tech_physics_lab_4","Omega Theory","en")
locList.addLoc("tech_engineering_lab_4_desc","Our material sciences reaches the point where we are capable of exploring the creation of self-shaping and self-designing nanoware.","en")
locList.addLoc("tech_engineering_lab_4","Smart-Matter Theory","en")
locList.addLoc("tech_agricultural_processing_1_desc","Nano technologies that were originally developed to enhance our starbases, allow us to significantly increase the output of our farms and $hydroponic_farm$s.","en")
locList.addLoc("tech_agricultural_processing_1","$advanced$ Agricultural Processing","en")
locList.addLoc("tech_agricultural_processing_2_desc","The use of $advanced$ robotic technologies allows us to further automate and enhance the processing of organic matter into consumption grade food.","en")
locList.addLoc("tech_agricultural_processing_2","$superior$ Agricultural Processing","en")
locList.addLoc("tech_hyperstorage_1","Hyperstorage","en")
locList.addLoc("tech_hyperstorage_1_desc","Storage formulated as a scientific problem will lead to the emergence of a new paradigm.","en")
locList.addLoc("tech_hyperstorage_2","$advanced$ Hyperstorage","en")
locList.addLoc("tech_hyperstorage_2_desc","Recent advances in the study of nanometric storage can substantially increase the efficiency of our hyperstorage facilities.","en")
locList.addLoc("tech_hyperstorage_3","$superior$ Hyperstorage","en")
locList.addLoc("tech_hyperstorage_3_desc","Recent advances in the study of entropy allow us to increase the efficiency of our hyperstorage facilities even further.","en")

### Strategic Resources

locList.addLoc("sr_megastructure_node","Megastructure Node","en")
locList.addLoc("sr_megastructure_node_desc","Megastructure Nodes represent structural junctures where the megastructure's internal energy matrix can be expanded.","en")


### Modifiers

locList.addLoc("capital_building_build_cost_mult","Capital Buildings Build Cost Multiplier","en")
locList.addLoc("capital_building_construction_speed_mult","Capital Buildings Construction Speed Multiplier","en")
locList.addLoc("empire_unique_building_build_cost_mult","Empire Unique Buildings Build Cost Multiplier","en")
locList.addLoc("empire_unique_building_construction_speed_mult","Empire Unique Buildings Construction Speed Multiplier","en")
locList.addLoc("planet_unique_building_build_cost_mult","Planet Unique Buildings Build Cost Multiplier","en")
locList.addLoc("planet_unique_building_construction_speed_mult","Planet Unique Buildings Construction Speed Multiplier","en")
locList.addLoc("military_building_build_cost_mult","Military Buildings Build Cost Multiplier","en")
locList.addLoc("military_building_construction_speed_mult","Military Buildings Construction Speed Multiplier","en")
locList.addLoc("standard_resource_building_build_cost_mult","Standard Resource Buildings Build Cost Multiplier","en")
locList.addLoc("standard_resource_building_construction_speed_mult","Standard Resource Buildings Construction Speed Multiplier","en")
locList.addLoc("research_resource_building_build_cost_mult","Research Resource Buildings Build Cost Multiplier","en")
locList.addLoc("research_resource_building_construction_speed_mult","Research Resource Buildings Construction Speed Multiplier","en")
locList.addLoc("unity_resource_building_build_cost_mult","Unity Resource Buildings Build Cost Multiplier","en")
locList.addLoc("unity_resource_building_construction_speed_mult","Unity Resource Buildings Construction Speed Multiplier","en")
locList.addLoc("special_resource_building_build_cost_mult","Special Resource Buildings Build Cost Multiplier","en")
locList.addLoc("special_resource_building_construction_speed_mult","Special Resource Buildings Construction Speed Multiplier","en")
locList.addLoc("replicator_building_build_cost_mult","Replicator Buildings Build Cost Multiplier","en")
locList.addLoc("replicator_building_construction_speed_mult","Replicator Buildings Construction Speed Multiplier","en")

### Triggered Planet Modifiers Keys

locList.addLoc("capital_3_resource_bonus_modifier","T5 Empire Capital Bonus","en")
locList.addLoc("capital_3_resource_bonus_modifier_desc","This is a special bonus given by t5 resource building on a planet with an empire capital.","en")
locList.addLoc("power_plant_5_regular_capital_modifier","T5 Power Plant Empire Capital Bonus","en")
locList.addLoc("power_plant_5_ringworld_capital_modifier","T5 Power Plant Empire Capital Bonus (Ringworld)","en")
locList.addLoc("mining_network_5_regular_capital_modifier","T5 Mining Network Empire Capital Bonus","en")
locList.addLoc("mining_network_5_ringworld_capital_modifier","T5 Mining Network Empire Capital Bonus (Ringworld)","en")
locList.addLoc("hydroponics_farm_5_regular_capital_modifier","T5 Hydroponic Farms Empire Capital Bonus","en")
locList.addLoc("hydroponics_farm_5_ringworld_capital_modifier","T5 Hydroponic Farms Empire Capital Bonus (Ringworld)","en")
locList.addLoc("engineering_facility_4_regular_capital_modifier","T5 Engineering Facility Empire Capital Bonus","en")
locList.addLoc("engineering_facility_4_ringworld_capital_modifier","T5 Engineering Facility Empire Capital Bonus (Ringworld)","en")
locList.addLoc("physics_lab_4_regular_capital_modifier","T5 $physics_lab$ Empire Capital Bonus","en")
locList.addLoc("physics_lab_4_ringworld_capital_modifier","T5 $physics_lab$ Empire Capital Bonus (Ringworld)","en")
locList.addLoc("biolab_4_regular_capital_modifier","T5 Biolab Empire Capital Bonus","en")
locList.addLoc("biolab_4_ringworld_capital_modifier","T5 Biolab Empire Capital Bonus (Ringworld)","en")

### Building Localisations

locList.addLoc("mining_complex","Mining Complex","en")
locList.addLoc("mining_complex_desc","Mining Complexes are §Htile restricted§! buildings that can only be built on a tile containing minerals £minerals.\n They have a base produced resource output that is dependent on the building's specific tier §H+200%§! the amount of minerals £minerals on the tile on which they are built.","en")
locList.addLoc("farming_complex","Farming Complex","en")
locList.addLoc("farming_complex_desc","Farming Complexes are §Htile restricted§! buildings that can only be built on a tile containing food £food.\n They have a base produced resource output that is dependent on the building's specific tier §H+200%§! the amount of food £food on the tile on which they are built.","en")
locList.addLoc("isotope_refinery","Isotope Refinery","en")
locList.addLoc("isotope_refinery_desc","Isotope Refineries are §Htile restricted§! buildings that can only be built on a tile containing energy £energy.\n They have a base produced resource output that is dependent on the building's specific tier §H+200%§! the amount of energy £energy on the tile on which they are built.","en")
locList.addLoc("biofuel_refinery","Biofuel Refinery","en")
locList.addLoc("biofuel_refinery_desc","Biofuel Refineries are §Htile restricted§! buildings that can only be built on a tile containing food £food.\n They have a base produced resource output that is dependent on the building's specific tier §H+100%§! the amount of food £food on the tile on which they are built converted to energy £energy.","en")
locList.addLoc("society_lab","Society Lab","en")
locList.addLoc("society_lab_desc","Society Labs are §Htile restricted§! buildings that can only be built on a tile containing society research £society.\n They have a base produced resource output that is dependent on the building's specific tier §H+200%§! the amount of society research £society on the tile on which they are built.","en")
locList.addLoc("physics_lab","Physics Lab","en")
locList.addLoc("physics_lab_desc","Society Labs are §Htile restricted§! buildings that can only be built on a tile containing society research £society.\n They have a base produced resource output that is dependent on the building's specific tier §H+200%§! the amount of society research £society on the tile on which they are built.","en")
locList.addLoc("engineering_lab","Engineering Lab","en")
locList.addLoc("engineering_lab_desc","Engineering Labs are §Htile restricted§! buildings that can only be built on a tile containing engineering research £engineering.\n They have a base produced resource output that is dependent on the building's specific tier §H+200%§! the amount of engineering research £engineering on the tile on which they are built.","en")
locList.addLoc("energy_matter_converter","Energy-Matter Converter","en")
locList.addLoc("energy_matter_converter_desc","Energy-Matter Converters are special §Htile restricted§! buildings that can only be built on a tile containing a megastructure node £megastructure_node.\n They have a static produced output of §H+3§! minerals £minerals but they give a powerful minerals £minerals adjacency bonus that scales relative to the amount of megastructure node £megastructure_node points on the tile on which they are built as well as their tier.","en")
locList.addLoc("energy_conduit","Energy Conduit","en")
locList.addLoc("energy_conduit_desc","Energy Conduits are special §Htile restricted§! buildings that can only be built on a tile containing a megastructure node £megastructure_node.\n They have a static produced output of §H+3§! energy £energy but they give a powerful energy £energy adjacency bonus that scales relative to the amount of megastructure node £megastructure_node points on the tile on which they are built as well as their tier.","en")
locList.addLoc("food_replicator","Food Replicator","en")
locList.addLoc("food_replicator_desc","Food Replicators are special §Htile restricted§! buildings that can only be built on a tile containing a megastructure node £megastructure_node.\n They have a static produced output of §H+3§! food £food but they give a powerful food £food adjacency bonus that scales relative to the amount of megastructure node £megastructure_node points on the tile on which they are built as well as their tier.","en")
locList.addLoc("computational_array","Computational Array","en")
locList.addLoc("computational_array_desc","Computational Arrays are special §Htile restricted§! buildings that can only be built on a tile containing a megastructure node £megastructure_node.\n They have a static produced output of §H+1/+1/+1§! society £society, physics £physics and engineering £engineering but they give a powerful adjacency bonus to all research buildings that scales relative to the amount of megastructure node £megastructure_node points on the tile on which they are built as well as their tier.","en")
locList.addLoc("economic_district","Economic District","en")
locList.addLoc("economic_district_desc","Economic Districts are non-restricted energy £energy producing buildings. These buildings represent centers of commerce and economic development.\n They have both a base produced resource output and a static resource output that scale respective of the building's specific tier.","en")
locList.addLoc("manufacturing_complex","Manufacturing Complex","en")
locList.addLoc("manufacturing_complex_desc","Manufacturing Complexes are non-restricted minerals £minerals producing buildings. These buildings represent centers of industrial production and development.\n They have both a base produced resource output and a static resource output that scale respective of the building's specific tier.","en")
locList.addLoc("hydroponic_farm","Hydroponic Compound","en")
locList.addLoc("hydroponic_farm_desc","Hydroponic Compound are non-restricted food £food producing buildings. These buildings represent tightly controlled self-containing biospheres that are dedicated to food production.\n They have both a base produced resource output and a static resource output that scale respective of the building's specific tier.","en")
locList.addLoc("sociological_campus","Sociological Campus","en")
locList.addLoc("sociological_campus_desc","Sociological Campuses are non-restricted society research £society producing buildings. These buildings represent centers of scientific research and development.\n They have both a base produced resource output and a static resource output that scale respective of the building's specific tier.","en")
locList.addLoc("physics_campus","Physics Campus","en")
locList.addLoc("physics_campus_desc","Physics Campuses are non-restricted physics research £physics producing buildings. These buildings represent centers of scientific research and development.\n They have both a base produced resource output and a static resource output that scale respective of the building's specific tier.","en")
locList.addLoc("engineering_campus","Engineering Campus","en")
locList.addLoc("engineering_campus_desc","Engineering Campuses are non-restricted engineering research £engineering producing buildings. These buildings represent centers of scientific research and development.\n They have both a base produced resource output and a static resource output that scale respective of the building's specific tier.","en")
locList.addLoc("agricultural_processor","Agricultural Processor","en")
locList.addLoc("agricultural_processor_desc","Agricultural Processing Plants produce some food £food on their own, but more importantly increase the overall food £food output of the planet.","en")
locList.addLoc("hyperstorage_facility","Hyperstorage Facility","en")
locList.addLoc("hyperstorage_facility_desc","Hyperstorage facilities utilize cutting edge stasis and vacuum manipulation technologies to store materials.\n\n While these buildings produce some minerals £minerals for machine empires and food £food and minerals £minerals for organic empires, their main advantage appears when an empire suffers from a §RMineral Deficit§!, §REnergy Deficit§! or, in the case of organic empires, §RStarvation§!. When this occurs, the hyperstorage facility will begin to output large quantities of up to §Gtwo required resources§!.","en")

### Generic Keys - these are used for the different variations of the buildings
locList.addLoc("cgm_building_mining_complex_1","$mining_complex$ I","en")
locList.addLoc("cgm_building_mining_complex_1_desc","$basic$ $mining_complex$.\n\n$mining_complex_desc$","en")
locList.addLoc("cgm_building_mining_complex_2","$mining_complex$ II","en")
locList.addLoc("cgm_building_mining_complex_2_desc","$improved$ $mining_complex$.\n\n$mining_complex_desc$","en")
locList.addLoc("cgm_building_mining_complex_3","$mining_complex$ III","en")
locList.addLoc("cgm_building_mining_complex_3_desc","$enhanced$ $mining_complex$.\n\n$mining_complex_desc$","en")
locList.addLoc("cgm_building_mining_complex_4","$mining_complex$ IV","en")
locList.addLoc("cgm_building_mining_complex_4_desc","$advanced$ $mining_complex$.\n\n$mining_complex_desc$","en")
locList.addLoc("cgm_building_mining_complex_5","$mining_complex$ V","en")
locList.addLoc("cgm_building_mining_complex_5_desc","$superior$ $mining_complex$.\n\n$mining_complex_desc$","en")
locList.addLoc("cgm_building_farming_complex_1","$farming_complex$ I","en")
locList.addLoc("cgm_building_farming_complex_1_desc","$basic$ $farming_complex$.\n\n$farming_complex_desc$","en")
locList.addLoc("cgm_building_farming_complex_2","$farming_complex$ II","en")
locList.addLoc("cgm_building_farming_complex_2_desc","$improved$ $farming_complex$.\n\n$farming_complex_desc$","en")
locList.addLoc("cgm_building_farming_complex_3","$farming_complex$ III","en")
locList.addLoc("cgm_building_farming_complex_3_desc","$enhanced$ $farming_complex$.\n\n$farming_complex_desc$","en")
locList.addLoc("cgm_building_farming_complex_4","$farming_complex$ IV","en")
locList.addLoc("cgm_building_farming_complex_4_desc","$advanced$ $farming_complex$.\n\n$farming_complex_desc$","en")
locList.addLoc("cgm_building_farming_complex_5","$farming_complex$ V","en")
locList.addLoc("cgm_building_farming_complex_5_desc","$superior$ $farming_complex$.\n\n$farming_complex_desc$","en")
locList.addLoc("cgm_building_isotope_refinery_1","$isotope_refinery$ I","en")
locList.addLoc("cgm_building_isotope_refinery_1_desc","$basic$ $isotope_refinery$.\n\n$isotope_refinery_desc$","en")
locList.addLoc("cgm_building_isotope_refinery_2","$isotope_refinery$ II","en")
locList.addLoc("cgm_building_isotope_refinery_2_desc","$improved$ $isotope_refinery$.\n\n$isotope_refinery_desc$","en")
locList.addLoc("cgm_building_isotope_refinery_3","$isotope_refinery$ III","en")
locList.addLoc("cgm_building_isotope_refinery_3_desc","$enhanced$ $isotope_refinery$.\n\n$isotope_refinery_desc$","en")
locList.addLoc("cgm_building_isotope_refinery_4","$isotope_refinery$ IV","en")
locList.addLoc("cgm_building_isotope_refinery_4_desc","$advanced$ $isotope_refinery$.\n\n$isotope_refinery_desc$","en")
locList.addLoc("cgm_building_isotope_refinery_5","$isotope_refinery$ V","en")
locList.addLoc("cgm_building_isotope_refinery_5_desc","$superior$ $isotope_refinery$.\n\n$isotope_refinery_desc$","en")
locList.addLoc("cgm_building_biofuel_refinery_1","$biofuel_refinery$ I","en")
locList.addLoc("cgm_building_biofuel_refinery_1_desc","$basic$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","en")
locList.addLoc("cgm_building_biofuel_refinery_2","$biofuel_refinery$ II","en")
locList.addLoc("cgm_building_biofuel_refinery_2_desc","$improved$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","en")
locList.addLoc("cgm_building_biofuel_refinery_3","$biofuel_refinery$ III","en")
locList.addLoc("cgm_building_biofuel_refinery_3_desc","$enhanced$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","en")
locList.addLoc("cgm_building_biofuel_refinery_4","$biofuel_refinery$ IV","en")
locList.addLoc("cgm_building_biofuel_refinery_4_desc","$advanced$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","en")
locList.addLoc("cgm_building_biofuel_refinery_5","$biofuel_refinery$ V","en")
locList.addLoc("cgm_building_biofuel_refinery_5_desc","$superior$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","en")
locList.addLoc("cgm_building_society_lab_1","$society_lab$ I","en")
locList.addLoc("cgm_building_society_lab_1_desc","$basic$ $society_lab$.\n\n$society_lab_desc$","en")
locList.addLoc("cgm_building_society_lab_2","$society_lab$ II","en")
locList.addLoc("cgm_building_society_lab_2_desc","$improved$ $society_lab$.\n\n$society_lab_desc$","en")
locList.addLoc("cgm_building_society_lab_3","$society_lab$ III","en")
locList.addLoc("cgm_building_society_lab_3_desc","$enhanced$ $society_lab$.\n\n$society_lab_desc$","en")
locList.addLoc("cgm_building_society_lab_4","$society_lab$ IV","en")
locList.addLoc("cgm_building_society_lab_4_desc","$advanced$ $society_lab$.\n\n$society_lab_desc$","en")
locList.addLoc("cgm_building_society_lab_5","$society_lab$ V","en")
locList.addLoc("cgm_building_society_lab_5_desc","$superior$ $society_lab$.\n\n$society_lab_desc$","en")
locList.addLoc("cgm_building_physics_lab_1","$physics_lab$ I","en")
locList.addLoc("cgm_building_physics_lab_1_desc","$basic$ $physics_lab$.\n\n$physics_lab_desc$","en")
locList.addLoc("cgm_building_physics_lab_2","$physics_lab$ II","en")
locList.addLoc("cgm_building_physics_lab_2_desc","$improved$ $physics_lab$.\n\n$physics_lab_desc$","en")
locList.addLoc("cgm_building_physics_lab_3","$physics_lab$ III","en")
locList.addLoc("cgm_building_physics_lab_3_desc","$enhanced$ $physics_lab$.\n\n$physics_lab_desc$","en")
locList.addLoc("cgm_building_physics_lab_4","$physics_lab$ IV","en")
locList.addLoc("cgm_building_physics_lab_4_desc","$advanced$ $physics_lab$.\n\n$physics_lab_desc$","en")
locList.addLoc("cgm_building_physics_lab_5","$physics_lab$ V","en")
locList.addLoc("cgm_building_physics_lab_5_desc","$superior$ $physics_lab$.\n\n$physics_lab_desc$","en")
locList.addLoc("cgm_building_engineering_lab_1","$engineering_lab$ I","en")
locList.addLoc("cgm_building_engineering_lab_1_desc","$basic$ $engineering_lab$.\n\n$engineering_lab_desc$","en")
locList.addLoc("cgm_building_engineering_lab_2","$engineering_lab$ II","en")
locList.addLoc("cgm_building_engineering_lab_2_desc","$improved$ $engineering_lab$.\n\n$engineering_lab_desc$","en")
locList.addLoc("cgm_building_engineering_lab_3","$engineering_lab$ III","en")
locList.addLoc("cgm_building_engineering_lab_3_desc","$enhanced$ $engineering_lab$.\n\n$engineering_lab_desc$","en")
locList.addLoc("cgm_building_engineering_lab_4","$engineering_lab$ IV","en")
locList.addLoc("cgm_building_engineering_lab_4_desc","$advanced$ $engineering_lab$.\n\n$engineering_lab_desc$","en")
locList.addLoc("cgm_building_engineering_lab_5","$engineering_lab$ V","en")
locList.addLoc("cgm_building_engineering_lab_5_desc","$superior$ $engineering_lab$.\n\n$engineering_lab_desc$","en")
locList.addLoc("cgm_building_energy_matter_converter_1","$energy_matter_converter$ I","en")
locList.addLoc("cgm_building_energy_matter_converter_1_desc","$basic$ $energy_matter_converter$.\n\n$energy_matter_converter_desc$","en")
locList.addLoc("cgm_building_energy_matter_converter_2","$energy_matter_converter$ II","en")
locList.addLoc("cgm_building_energy_matter_converter_2_desc","$improved$ $energy_matter_converter$.\n\n$energy_matter_converter_desc$","en")
locList.addLoc("cgm_building_energy_matter_converter_3","$energy_matter_converter$ III","en")
locList.addLoc("cgm_building_energy_matter_converter_3_desc","$enhanced$ $energy_matter_converter$.\n\n$energy_matter_converter_desc$","en")
locList.addLoc("cgm_building_energy_conduit_1","$energy_conduit$ I","en")
locList.addLoc("cgm_building_energy_conduit_1_desc","$basic$ $energy_conduit$.\n\n$energy_conduit_desc$","en")
locList.addLoc("cgm_building_energy_conduit_2","$energy_conduit$ II","en")
locList.addLoc("cgm_building_energy_conduit_2_desc","$improved$ $energy_conduit$.\n\n$energy_conduit_desc$","en")
locList.addLoc("cgm_building_energy_conduit_3","$energy_conduit$ III","en")
locList.addLoc("cgm_building_energy_conduit_3_desc","$enhanced$ $energy_conduit$.\n\n$energy_conduit_desc$","en")
locList.addLoc("cgm_building_food_replicator_1","$food_replicator$ I","en")
locList.addLoc("cgm_building_food_replicator_1_desc","$basic$ $food_replicator$.\n\n$food_replicator_desc$","en")
locList.addLoc("cgm_building_food_replicator_2","$food_replicator$ II","en")
locList.addLoc("cgm_building_food_replicator_2_desc","$improved$ $food_replicator$.\n\n$food_replicator_desc$","en")
locList.addLoc("cgm_building_food_replicator_3","$food_replicator$ III","en")
locList.addLoc("cgm_building_food_replicator_3_desc","$enhanced$ $food_replicator$.\n\n$food_replicator_desc$","en")
locList.addLoc("cgm_building_computational_array_1","$computational_array$ I","en")
locList.addLoc("cgm_building_computational_array_1_desc","$basic$ $computational_array$.\n\n$computational_array_desc$","en")
locList.addLoc("cgm_building_computational_array_2","$computational_array$ II","en")
locList.addLoc("cgm_building_computational_array_2_desc","$improved$ $computational_array$.\n\n$computational_array_desc$","en")
locList.addLoc("cgm_building_computational_array_3","$computational_array$ III","en")
locList.addLoc("cgm_building_computational_array_3_desc","$enhanced$ $computational_array$.\n\n$computational_array_desc$","en")

#### Building Localisations
locList.addLoc("building_economic_district_1","$economic_district$ I","en")
locList.addLoc("building_economic_district_1_desc","$basic$ $economic_district$.\n\n$economic_district_desc$","en")
locList.addLoc("building_economic_district_2","$economic_district$ II","en")
locList.addLoc("building_economic_district_2_desc","$improved$ $economic_district$.\n\n$economic_district_desc$","en")
locList.addLoc("building_economic_district_3","$economic_district$ III","en")
locList.addLoc("building_economic_district_3_desc","$enhanced$ $economic_district$.\n\n$economic_district_desc$","en")
locList.addLoc("building_economic_district_4","$economic_district$ IV","en")
locList.addLoc("building_economic_district_4_desc","$advanced$ $economic_district$.\n\n$economic_district_desc$","en")
locList.addLoc("building_economic_district_5","$economic_district$ V","en")
locList.addLoc("building_economic_district_5_desc","$superior$ $economic_district$.\n\n$economic_district_desc$","en")
locList.addLoc("building_manufacturing_complex_1","$manufacturing_complex$ I","en")
locList.addLoc("building_manufacturing_complex_1_desc","$basic$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","en")
locList.addLoc("building_manufacturing_complex_2","$manufacturing_complex$ II","en")
locList.addLoc("building_manufacturing_complex_2_desc","$improved$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","en")
locList.addLoc("building_manufacturing_complex_3","$manufacturing_complex$ III","en")
locList.addLoc("building_manufacturing_complex_3_desc","$enhanced$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","en")
locList.addLoc("building_manufacturing_complex_4","$manufacturing_complex$ IV","en")
locList.addLoc("building_manufacturing_complex_4_desc","$advanced$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","en")
locList.addLoc("building_manufacturing_complex_5","$manufacturing_complex$ V","en")
locList.addLoc("building_manufacturing_complex_5_desc","$superior$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","en")
locList.addLoc("building_hydroponic_farm_1","$hydroponic_farm$ I","en")
locList.addLoc("building_hydroponic_farm_1_desc","$basic$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","en")
locList.addLoc("building_hydroponic_farm_2","$hydroponic_farm$ II","en")
locList.addLoc("building_hydroponic_farm_2_desc","$improved$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","en")
locList.addLoc("building_hydroponic_farm_3","$hydroponic_farm$ III","en")
locList.addLoc("building_hydroponic_farm_3_desc","$enhanced$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","en")
locList.addLoc("building_hydroponic_farm_4","$hydroponic_farm$ IV","en")
locList.addLoc("building_hydroponic_farm_4_desc","$advanced$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","en")
locList.addLoc("building_hydroponic_farm_5","$hydroponic_farm$ V","en")
locList.addLoc("building_hydroponic_farm_5_desc","$superior$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","en")
locList.addLoc("building_sociological_campus_1","$sociological_campus$ I","en")
locList.addLoc("building_sociological_campus_1_desc","$basic$ $sociological_campus$.\n\n$sociological_campus_desc$","en")
locList.addLoc("building_sociological_campus_2","$sociological_campus$ II","en")
locList.addLoc("building_sociological_campus_2_desc","$improved$ $sociological_campus$.\n\n$sociological_campus_desc$","en")
locList.addLoc("building_sociological_campus_3","$sociological_campus$ III","en")
locList.addLoc("building_sociological_campus_3_desc","$enhanced$ $sociological_campus$.\n\n$sociological_campus_desc$","en")
locList.addLoc("building_sociological_campus_4","$sociological_campus$ IV","en")
locList.addLoc("building_sociological_campus_4_desc","$advanced$ $sociological_campus$.\n\n$sociological_campus_desc$","en")
locList.addLoc("building_sociological_campus_5","$sociological_campus$ V","en")
locList.addLoc("building_sociological_campus_5_desc","$superior$ $sociological_campus$.\n\n$sociological_campus_desc$","en")
locList.addLoc("building_physics_campus_1","$physics_campus$ I","en")
locList.addLoc("building_physics_campus_1_desc","$basic$ $physics_campus$.\n\n$physics_campus_desc$","en")
locList.addLoc("building_physics_campus_2","$physics_campus$ II","en")
locList.addLoc("building_physics_campus_2_desc","$improved$ $physics_campus$.\n\n$physics_campus_desc$","en")
locList.addLoc("building_physics_campus_3","$physics_campus$ III","en")
locList.addLoc("building_physics_campus_3_desc","$enhanced$ $physics_campus$.\n\n$physics_campus_desc$","en")
locList.addLoc("building_physics_campus_4","$physics_campus$ IV","en")
locList.addLoc("building_physics_campus_4_desc","$advanced$ $physics_campus$.\n\n$physics_campus_desc$","en")
locList.addLoc("building_physics_campus_5","$physics_campus$ V","en")
locList.addLoc("building_physics_campus_5_desc","$superior$ $physics_campus$.\n\n$physics_campus_desc$","en")
locList.addLoc("building_engineering_campus_1","$engineering_campus$ I","en")
locList.addLoc("building_engineering_campus_1_desc","$basic$ $engineering_campus$.\n\n$engineering_campus_desc$","en")
locList.addLoc("building_engineering_campus_2","$engineering_campus$ II","en")
locList.addLoc("building_engineering_campus_2_desc","$improved$ $engineering_campus$.\n\n$engineering_campus_desc$","en")
locList.addLoc("building_engineering_campus_3","$engineering_campus$ III","en")
locList.addLoc("building_engineering_campus_3_desc","$enhanced$ $engineering_campus$.\n\n$engineering_campus_desc$","en")
locList.addLoc("building_engineering_campus_4","$engineering_campus$ IV","en")
locList.addLoc("building_engineering_campus_4_desc","$advanced$ $engineering_campus$.\n\n$engineering_campus_desc$","en")
locList.addLoc("building_engineering_campus_5","$engineering_campus$ V","en")
locList.addLoc("building_engineering_campus_5_desc","$superior$ $engineering_campus$.\n\n$engineering_campus_desc$","en")
locList.addLoc("building_agricultural_processor_1","$agricultural_processor$ I","en")
locList.addLoc("building_agricultural_processor_2","$agricultural_processor$ II","en")
locList.addLoc("building_hyperstorage_facility_1","$hyperstorage_facility$ I","en")
locList.addLoc("building_hyperstorage_facility_2","$hyperstorage_facility$ II","en")
locList.addLoc("building_hyperstorage_facility_3","$hyperstorage_facility$ III","en")

##### buildings that use a key for localisations

# Debug Resource - these can be turned on to expose the AI logic

locList.addLoc("sr_null_e_desc","REPLACE_ME","en")
locList.addLoc("sr_null_e","Energy Building Tile","en")
locList.addLoc("sr_null_en_desc","REPLACE_ME","en")
locList.addLoc("sr_null_en","Engineering Building Tile","en")
locList.addLoc("sr_null_f_desc","REPLACE_ME","en")
locList.addLoc("sr_null_f","Food Building Tile","en")
locList.addLoc("sr_null_m_desc","REPLACE_ME","en")
locList.addLoc("sr_null_m","Minerals Building Tile","en")
locList.addLoc("sr_null_py_desc","REPLACE_ME","en")
locList.addLoc("sr_null_py","Physics Building Tile","en")
locList.addLoc("sr_null_sc_desc","REPLACE_ME","en")
locList.addLoc("sr_null_sc","Society Building Tile","en")
locList.addLoc("sr_null_u_desc","REPLACE_ME","en")
locList.addLoc("sr_null_u","Unity Building Tile","en")

### Deposits - these do not actually require a localisation. The localisations below are just placeholder to remove error messages in CWTools

locList.addLoc("1_mining_station_energy","REPLACE_ME","en")
locList.addLoc("1_mining_station_minerals","REPLACE_ME","en")
locList.addLoc("1_mining_station_food","REPLACE_ME","en")
locList.addLoc("1_mining_station_unity","REPLACE_ME","en")
locList.addLoc("1_mining_station_society_research","REPLACE_ME","en")
locList.addLoc("1_mining_station_physics_research","REPLACE_ME","en")
locList.addLoc("1_mining_station_engineering_research","REPLACE_ME","en")
locList.addLoc("1_research_station_energy","REPLACE_ME","en")
locList.addLoc("1_research_station_minerals","REPLACE_ME","en")
locList.addLoc("1_research_station_food","REPLACE_ME","en")
locList.addLoc("1_research_station_unity","REPLACE_ME","en")
locList.addLoc("1_research_station_society_research","REPLACE_ME","en")
locList.addLoc("1_research_station_physics_research","REPLACE_ME","en")
locList.addLoc("1_research_station_engineering_research","REPLACE_ME","en")
locList.addLoc("energy_building_tile","REPLACE_ME","en")
locList.addLoc("minerals_building_tile","REPLACE_ME","en")
locList.addLoc("food_building_tile","REPLACE_ME","en")
locList.addLoc("unity_building_tile","REPLACE_ME","en")
locList.addLoc("society_research_building_tile","REPLACE_ME","en")
locList.addLoc("engineering_research_building_tile","REPLACE_ME","en")
locList.addLoc("physics_research_building_tile","REPLACE_ME","en")
locList.addLoc("special_resource_tile","REPLACE_ME","en")
locList.addLoc("d_megastructure_node","REPLACE_ME","en")
