
### Menu Options
locList.addLoc("basic","Grundlegend","de")
locList.addLoc("improved","Verbessert","de")
locList.addLoc("enhanced","Erweitert","de")
locList.addLoc("advanced","Fortgeschritten","de")
locList.addLoc("Superior","Ausgezeichnet","de")
locList.addLoc("optimal","Optimal","de")

locList.addLoc("edict_cgm_menu_edict_desc","Dieses Edikt öffnet das CGM Menu.","de")
locList.addLoc("edict_cgm_menu_edict","CGM Menu öffnen","de")
locList.addLoc("cgm_buildings_text","Kernmechanik: Gebäude","de")
locList.addLoc("cgm_main_menu_close_desc","Menu schließen","de")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_name","Inhalt aktivieren: CGM Gebäude","de")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_desc","Diese Option aktiviert die CGM Gebäude. Alle standard vanilla Ressourcen-Gebäude, z.B. Minen Komplexe und Kraftwerke, werden automatisch ersetzt und jede notwendige Technologie, die fehlt, wird automatisch hinzugefügt.\n Wichtig! Diese Option ist nur am Spielstart verfügbar und kann nicht wieder rückgängig gemacht werden!","de")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_name","Gebäude aus dem Basisspiel behalten","de")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_desc","Diese Option aktiviert die Ressourcenwerte für Gebäude aus dem Basisspiel. Keine Änderungen werden an Gebäuden oder Technologien vorgenommen. Diese Option öffnet weitere Einstellungsmöglichkeiten","de")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_name","Aktiviere überarbeitete Gebäudewerte","de")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_desc","Diese Option aktiviert überabeitete Gebäudewerte. Einige Gebäude werden anderen Ressourcen, Planeten-Modifikatoren usw. haben, die vom Basisspiel abweichen. Diese Option kann jederzeit während des Spiels an- und ausgeschaltet werden.","de")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_name","Deaktiviere überarbeitete Gebäudewerte","de")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_desc","Diese Option deaktiviert überabeitete Gebäudewerte. Alle Werte werden wie im Basisspiel. Diese Option kann jederzeit während des Spiels an- und ausgeschaltet werden.","de")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_name","$advanced$e Gebäude Konfiguration","de")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_desc","Diese Option öffnet das fortgeschrittene Gebäudekonfigurationsmenu, das euch erlaubt Änderungen an den Kosten und Bauzeiten von bestimmten Gebäudekategorien zu ändern.","de")
locList.addLoc("cgm_main_menu_title","CGM Hauptmenu","de")
locList.addLoc("cgm_main_menu_desc","In diesem Menu könnt Ihr aussuchen, ob ihr lieber mit den Werten aus dem Basisspiel oder den Werten aus dem CGM Mod spielen wollt.\n\nWichtig: Wenn Ihr den Mod aktiviert, werden automatische ALLE Gebäude aus dem Basisspiel zu CGM Gebäuden konvertiert. Dies ist final.","de")
locList.addLoc("cgm_main_menu_header","Spielkernmechaniken Menu","de")
locList.addLoc("cgm_main_menu_close_name","Menu schließen","de")

#Allow Stuff

locList.addLoc("requires_non_machine_empire_capital","Erfordert einen §HRegierungssitz§!.","de")
locList.addLoc("requires_building_capital_0","Erfordert irgendein §Hplanetares Verwaltungsgebäude§!.","de")
locList.addLoc("requires_building_capital_0_or_hab","Erfordert irgendein §HVerwaltungsgebäude§!.","de")
locList.addLoc("requires_building_hab_capital","Erfordert §H$building_hab_capital$§! oder eine §HRegierungssitz§!.","de")
locList.addLoc("requires_building_capital_2_or_hab","Erfordert §HPlanetare Hauptstadt§! oder §H$building_hab_capital$§!.","de")
locList.addLoc("requires_energy_tile","Erfordert Energie £energy auf dem Feld.","de")
locList.addLoc("requires_minerals_tile","Erfordert Mineralien £minerals auf dem Feld.","de")
locList.addLoc("requires_food_tile","Erfordert Nahrung £food auf dem Feld.","de")
locList.addLoc("requires_engineering_research_tile","Erfordert Ingenieur-Forschung £engineering auf dem Feld.","de")
locList.addLoc("requires_physics_research_tile","Erfordert Physik-Forschung £physics auf dem Feld.","de")
locList.addLoc("requires_society_research_tile","Erfordert Sozial-Forschung £society auf dem Feld.","de")
locList.addLoc("requires_megastructure_node_tile","Erfordert Megastruktur-Knoten £megastructure_node auf dem Feld.","de")

locList.addLoc("tech_biofuel_refining_1_desc","Komplexe organische Materie kann in günstigen Treibstoff verwandelt werden. Auch wenn es nicht so effizient wie die Synthetisierung radioaktive Isotrope ist, organische Materie ist weitaus verbreiteter.","de")
locList.addLoc("tech_biofuel_refining_1","$basic$ Bio-Treibstoff Raffinierung","de")
locList.addLoc("tech_biofuel_refining_2_desc","Die Wirksamkeit von Bio-Treibstoff kann $enhanced$ werden, indem wir genetisch veränderte Bakterien benutzen, die ein Pseudo-Öl absondern.","de")
locList.addLoc("tech_biofuel_refining_2","$enhanced$ Bio-Treibstoff Raffinierung","de")
locList.addLoc("tech_biofuel_refining_3_desc","Indem wir organische Moleküle auf der Nano-Skala manipulieren, sind wir in der Lage einen deutlich effizienteren Künstlichen Bio-Treibstoff erstellen.","de")
locList.addLoc("tech_biofuel_refining_3","$advanced$ Bio-Treibstoff Raffinierung","de")
locList.addLoc("tech_biofuel_refining_4_desc","Neue Synthetisierungsmethoden erlauben es uns festen Bio-Treibstoff zu gewinnen, welches den Transport vereinfacht und die Wirksamkeit erhöht.","de")
locList.addLoc("tech_biofuel_refining_4","Künstliche Bio-Treibstoff Kondensation","de")
locList.addLoc("tech_biofuel_refining_5_desc","Die Benutzung von Pico-Maschinen erlaubtes uns Bio-Treibstoff ohne Abfallprodukte herzustellen.","de")
locList.addLoc("tech_biofuel_refining_5","$optimal$ Bio-Treibstoff Raffinierung","de")
locList.addLoc("tech_power_plant_5_desc","Der Einsatz von Quantenkatalysatoren erlaubt usn enorm hohe Energie zu erzeugen.","de")
locList.addLoc("tech_power_plant_5","Quantum Isotope Synthetisierung","de")
locList.addLoc("tech_mining_network_5_desc","Der Einsatz von gravitonischen Bohrern erlaubt es uns schneller und präzischer in die tieferen Schichten einzudringen.","de")
locList.addLoc("tech_mining_network_5","$superior$e Minenarbeit","de")
locList.addLoc("tech_superior_agriculture_desc","Der Einsatz von nano-aktivem Untegrund erlaubt es uns die Ausbeute von Pflanzen zu erhöhren.","de")
locList.addLoc("tech_superior_agriculture","$superior$e Landwirtschaft","de")
locList.addLoc("tech_biolab_4_desc","Die Betrachtung von Zeit als einzelnes holistisches Kontinuum erlaubt es uns scheinbar isolierte Phänomene als eins fundamental vernetzt zu betrachten.","de")
locList.addLoc("tech_biolab_4","Holistische Psycho-Geschichte","de")
locList.addLoc("tech_physics_lab_4_desc","Die Theorieforschung hat eine Punkt erreicht an dem wir anfangen können die Omega Theorie zu erreichen. Diese erlaubt es nicht nur das Universum zu beschreiben sondern auch andere Dimensionen.","de")
locList.addLoc("tech_physics_lab_4","Omega Theorie","de")
locList.addLoc("tech_engineering_lab_4_desc","Unsere Forscher haben einen Punkt erreicht an dem wir Nanomaterial erforschen können, das sich selber formt und anpasst.","de")
locList.addLoc("tech_engineering_lab_4","Smart-Materie Theorie","de")
locList.addLoc("tech_agricultural_processing_1_desc","Nano Technologie, die ursprünglich zum Einsatz in Sternenstationen kam, kann nun genutzt werden um den Ertrag in unseren Farmen und $hydroponic_farm$en zu erhöhen.","de")
locList.addLoc("tech_agricultural_processing_1","$advanced$e Landwirtschaftliche Verarbeitung","de")
locList.addLoc("tech_agricultural_processing_2_desc","Der Einsatz von $advanced$er Robotor-Technologien erlaubt es uns den Verarbeitungsprozess weiter zu automatisieren.","de")
locList.addLoc("tech_agricultural_processing_2","$superior$e Landwirtschaftliche Verarbeitung","de")
locList.addLoc("tech_hyperstorage_1","Hyperlager","de")
locList.addLoc("tech_hyperstorage_1_desc","Lager, die als wissenschaftliches Problem formuliert wurden, die zur Erforschung neuer Paradigmen dienen.","de")
locList.addLoc("tech_hyperstorage_2","$advanced$ Hyperlager","de")
locList.addLoc("tech_hyperstorage_2_desc","Kürzliche Fortschritte bei der Untersuchung von Nanometerialien haben zu einer höheren Effizienz unserer Hyperlager geführt.","de")
locList.addLoc("tech_hyperstorage_3","$superior$ Hyperlager","de")
locList.addLoc("tech_hyperstorage_3_desc","Kürzliche Fortschritte bei der Untersuchung von Entropy haben zu einer höheren Effizienz unserer Hyperlager geführt.","de")

### Strategic Resources

locList.addLoc("sr_megastructure_node","Megastrukrurknoten","de")
locList.addLoc("sr_megastructure_node_desc","Megastrukrurknoten präsentieren strukurelle Ankerpunkte an denen die initiale Megastrukurenergiematrix erweitert werden kann.","de")


### Modifiers

locList.addLoc("capital_building_build_cost_mult","Verwaltungsgebäude Baukosten Multiplikator","de")
locList.addLoc("capital_building_construction_speed_mult","Verwaltungsgebäude Bauzeit Multiplikator","de")
locList.addLoc("empire_unique_building_build_cost_mult","Im Reich einzigartig Baukosten Multiplikator","de")
locList.addLoc("empire_unique_building_construction_speed_mult","Im Reich einzigartig Bauzeit Multiplikator","de")
locList.addLoc("planet_unique_building_build_cost_mult","Planetar einzigartig Baukosten Multiplikator","de")
locList.addLoc("planet_unique_building_construction_speed_mult","Planetar einzigartig Bauzeit Multiplikator","de")
locList.addLoc("military_building_build_cost_mult","Militär Baukosten Multiplikator","de")
locList.addLoc("military_building_construction_speed_mult","Militär Bauzeit Multiplikator","de")
locList.addLoc("standard_resource_building_build_cost_mult","Standard Ressourcengebäude Baukosten Multiplikator","de")
locList.addLoc("standard_resource_building_construction_speed_mult","Standard Ressourcengebäude Bauzeit Multiplikator","de")
locList.addLoc("research_resource_building_build_cost_mult","Forschungsgebäude Baukosten Multiplikator","de")
locList.addLoc("research_resource_building_construction_speed_mult","Forschungsgebäude Bauzeit Multiplikator","de")
locList.addLoc("unity_resource_building_build_cost_mult","Einigkeitsgebäude Baukosten Multiplikator","de")
locList.addLoc("unity_resource_building_construction_speed_mult","Einigkeitsgebäude Bauzeit Multiplikator","de")
locList.addLoc("special_resource_building_build_cost_mult","Spezialgebbäude Baukosten Multiplikator","de")
locList.addLoc("special_resource_building_construction_speed_mult","Spezialgebbäude Bauzeit Multiplikator","de")
locList.addLoc("replicator_building_build_cost_mult","Replikator Baukosten Multiplikator","de")
locList.addLoc("replicator_building_construction_speed_mult","Replikator Bauzeit Multiplikator","de")

### Triggered Planet Modifiers Keys

locList.addLoc("capital_3_resource_bonus_modifier","T5 Regierungssitz Bonus","de")
locList.addLoc("capital_3_resource_bonus_modifier_desc","Dies ist ein besonderer Bonus, von t5 resource Gebäuden auf einem Planeten mit einem Regierungssitz.","de")
locList.addLoc("power_plant_5_regular_capital_modifier","T5 Kraftwerk Regierungssitz Bonus","de")
locList.addLoc("power_plant_5_ringworld_capital_modifier","T5 Kraftwerk Regierungssitz Bonus (Ringwelt)","de")
locList.addLoc("mining_network_5_regular_capital_modifier","T5 Minennetzwerk Regierungssitz Bonus","de")
locList.addLoc("mining_network_5_ringworld_capital_modifier","T5 Minennetzwerk Regierungssitz Bonus (Ringwelt)","de")
locList.addLoc("hydroponics_farm_5_regular_capital_modifier","T5 Hydroponische Farmen Regierungssitz Bonus","de")
locList.addLoc("hydroponics_farm_5_ringworld_capital_modifier","T5 Hydroponische Farmen Regierungssitz Bonus (Ringwelt)","de")
locList.addLoc("engineering_facility_4_regular_capital_modifier","T5 Ingenieurs-Fakultät Regierungssitz Bonus","de")
locList.addLoc("engineering_facility_4_ringworld_capital_modifier","T5 Ingenieurs-Fakultät Regierungssitz Bonus (Ringwelt)","de")
locList.addLoc("physics_lab_4_regular_capital_modifier","T5 $physics_lab$ Regierungssitz Bonus","de")
locList.addLoc("physics_lab_4_ringworld_capital_modifier","T5 $physics_lab$ Regierungssitz Bonus (Ringwelt)","de")
locList.addLoc("biolab_4_regular_capital_modifier","T5 Biolab Regierungssitz Bonus","de")
locList.addLoc("biolab_4_ringworld_capital_modifier","T5 Biolab Regierungssitz Bonus (Ringwelt)","de")

### Building Localisations

locList.addLoc("mining_complex","Minenkomplex","de")
locList.addLoc("mining_complex_desc","Minenkomplexe sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Mineralien £minerals gebaut werden können. \n Sie haben eine Basisproduktion die von der Gebäudestufe abhängig ist und §H+100%§! der vorhandenen Feld-Mineralien £minerals","de")
locList.addLoc("farming_complex","Farmkomplex","de")
locList.addLoc("farming_complex_desc","Farmkomplexe sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Nahrung £food gebaut werden können. \n Sie haben eine Basisproduktion die von der Gebäudestufe abhängig ist und §H+100%§! der vorhandenen Feld-Nahrung £food.","de")
locList.addLoc("isotope_refinery","Isotope Raffinerie","de")
locList.addLoc("isotope_refinery_desc","Isotope Raffinerien sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Energie £energy gebaut werden können. \n Sie haben eine Basisproduktion die von der Gebäudestufe abhängig ist und §H+100%§! der vorhandenen Feld-Energie £energie.","de")
locList.addLoc("biofuel_refinery","Bio-Treibstoff Raffinerie","de")
locList.addLoc("biofuel_refinery_desc","Bio-Treibstoff Raffinerien sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Nahrung £food gebaut werden können. \n Sie haben eine Basisproduktion die von der Gebäudestufe abhängig ist und §H+100%§! der vorhandenen Feld-Nahrung £food, die in Energie £energie umgewandelt wird.","de")
locList.addLoc("society_lab","Sozial-Forschugnskomplexe","de")
locList.addLoc("society_lab_desc","Sozial-Forschugnskomplexe sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Sozial-Forschung £society gebaut werden können.\n Sie haben eine Basisproduktion die von der Gebäudestufe abhängig ist und §H+100%§! der vorhandenen Feld-Sozial-Forschung £society.","de")
locList.addLoc("physics_lab","Physik-Forschugnskomplexe","de")
locList.addLoc("physics_lab_desc","Physik-Forschugnskomplexe sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Physik-Forschung £physics gebaut werden können.\n Sie haben eine Basisproduktion die von der Gebäudestufe abhängig ist und §H+100%§! der vorhandenen Feld-Physik-Forschung £physics.","de")
locList.addLoc("engineering_lab","Ingenieur-Forschugnskomplexe","de")
locList.addLoc("engineering_lab_desc","Ingenieur-Forschugnskomplexe sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Ingenieur-Forschung £engineering gebaut werden können.\n Sie haben eine Basisproduktion die von der Gebäudestufe abhängig ist und §H+100%§! der vorhandenen Feld-Ingenieur-Forschung £engineering.","de")
locList.addLoc("energy_matter_converter","Energie-Masse Konvertierer","de")
locList.addLoc("energy_matter_converter_desc","Energie-Masse Konvertierer sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Megastrukrurknoten £megastructure_node gebaut werden können.\n Sie haben eine statische Produktion von §H+3§! Mineralien £minerals und geben einen starke Mineralien £minerals Nachbarschaftsbonus der mit der Anzahl an Megastrukrurknoten auf dem Feld als auch der Gebäudestufe skaliert.","de")
locList.addLoc("energy_conduit","Energie Leiter","de")
locList.addLoc("energy_conduit_desc","Energie Leiter sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Megastrukrurknoten £megastructure_node gebaut werden können.\n Sie haben eine statische Produktion von §H+3§! Energie £energy und geben einen starke Energie £energy Nachbarschaftsbonus der mit der Anzahl an Megastrukrurknoten auf dem Feld als auch der Gebäudestufe skaliert.","de")
locList.addLoc("food_replicator","Nahrungsreplikatoren","de")
locList.addLoc("food_replicator_desc","Nahrungsreplikatorens sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Megastrukrurknoten £megastructure_node gebaut werden können.\n Sie haben eine statische Produktion von §H+3§! Nahrung £food und geben einen starke Nahrung £food Nachbarschaftsbonus der mit der Anzahl an Megastrukrurknoten auf dem Feld als auch der Gebäudestufe skaliert.","de")
locList.addLoc("computational_array","Prozessoren-Array","de")
locList.addLoc("computational_array_desc","Prozessoren-Arrays sind §Hfeldbeschränkte§! Gebäude die nur auf Feldern mit Megastrukrurknoten £megastructure_node gebaut werden können.\n Sie haben eine statische Produktion von §H+1/+1/+1§! Sozial-Forschung £society, Physik-Forschung £physics and Ingenieur-Forschung £engineering und geben einen starke Forschungs Nachbarschaftsbonus der mit der Anzahl an Megastrukrurknoten auf dem Feld als auch der Gebäudestufe skaliert.","de")
locList.addLoc("economic_district","Ökonomischer Bezirk","de")
locList.addLoc("economic_district_desc","Ökonomische Bezirke sind nicht-feldbeschränkte Energie £energy produzierende Gebäude. Dieses Gebäude repräsentiert ein Zentrum von Handel und ökonomischer Weiterentwicklung.\n Sie haben sowohl einen Basiswert als auch einen statischen Anteil der nach Gebäudestufe skaliert.","de")
locList.addLoc("manufacturing_complex","Herstellungs-Komplex","de")
locList.addLoc("manufacturing_complex_desc","Herstellungs-Komplexe sind nicht-feldbeschränkte Mineralien £minerals produzierende Gebäude. Dieses Gebäude repräsentiert ein industrielles Zentrum.\n Sie haben sowohl einen Basiswert als auch einen statischen Anteil der nach Gebäudestufe skaliert.","de")
locList.addLoc("hydroponic_farm","Hydroponischer Verbund","de")
locList.addLoc("hydroponic_farm_desc","Hydroponische Verbunde sind nicht-feldbeschränkte Nahrung £food produzierende Gebäude. Diese Gebäude hoch-abgesicherte, selbstversorgende Biosphären, die zur Nahrungsgewinning eingesetzt werden.\n Sie haben sowohl einen Basiswert als auch einen statischen Anteil der nach Gebäudestufe skaliert.","de")
locList.addLoc("sociological_campus","Soziologische Fakultät","de")
locList.addLoc("sociological_campus_desc","Soziologische Fakultäten sind nicht-feldbeschränkte Sozial-Forschung £society produzierende Gebäude. Diese Gebäude bilden Zentren von wissenschaftlicher Forschung und Weiterentwicklung.\n Sie haben sowohl einen Basiswert als auch einen statischen Anteil der nach Gebäudestufe skaliert.","de")
locList.addLoc("physics_campus","Physik-Fakultät","de")
locList.addLoc("physics_campus_desc","Physik-Fakultäten sind nicht-feldbeschränkte Physik-Forschung £physics produzierende Gebäude. Diese Gebäude bilden Zentren von wissenschaftlicher Forschung und Weiterentwicklung.\n Sie haben sowohl einen Basiswert als auch einen statischen Anteil der nach Gebäudestufe skaliert.","de")
locList.addLoc("engineering_campus","Ingenierus-Fakultät","de")
locList.addLoc("engineering_campus_desc","Ingenierus-Fakultäten sind nicht-feldbeschränkte Ingenieurs-Forschung £engineering produzierende Gebäude. Diese Gebäude bilden Zentren von wissenschaftlicher Forschung und Weiterentwicklung.\n Sie haben sowohl einen Basiswert als auch einen statischen Anteil der nach Gebäudestufe skaliert.","de")
locList.addLoc("agricultural_processor","Landwirtschaftliche Prozessor","de")
locList.addLoc("agricultural_processor_desc","Landwirtschaftliche Prozessoren produzieren zwar nur wenig Nahrung £food an sich, reichern aber das Erdreich an, sodass es ergiebiger wird.","de")
locList.addLoc("hyperstorage_facility","Hyperlager","de")
locList.addLoc("hyperstorage_facility_desc","Hyperlager nutzen die neueste statis und Vakuum Manipulationstechniken um Materialien zu Lagern.\n\n Während dieser Lager für Maschinenimperien £minerals und Nahrung £food für organische Imperien produzieren, liegt ihr Wahrer nutzen darin, wenn es mal eine Ressourcenknappheit §RMineral Deficit§!, §REnergy Deficit§! oder, im Fall von organischen Imperien, §RStarvation§! gibt. Falls dies passiert, gibt das Hyperlager bis zu einem Wert von §Gtwo required resources§! frei.","de")

locList.addLoc("static_planet_resource_physics_research_add","Monatliche Physik Forschung","de")
locList.addLoc("static_planet_resource_engineering_research_add","Monatliche Engineering Forschung","de")
locList.addLoc("static_planet_resource_society_research_add","Monatliche Society Forschung","de")
