
### Menu Options

##These need to be translated
locList.addLoc("basic","Basique","fr")
locList.addLoc("improved","Optimisé","fr")
locList.addLoc("enhanced","Amélioré","fr")
locList.addLoc("advanced","Avancé","fr")
locList.addLoc("Superior","Supérieur","fr")
locList.addLoc("optimal","Optimal","fr")
locList.addLoc("tech_biofuel_refining_1_desc","La matière organnique complexe peut être convertie en carburant à bas coût. Bien que les isotopes radioactifs de synthese sont plus efficaces, la matière organique est bien plus commune.","fr")
locList.addLoc("tech_biofuel_refining_1","Raffinerie de biocarburant $basic$","fr")
locList.addLoc("tech_biofuel_refining_2_desc","Le rendement de notre biocarburant peut être $enhanced$e par l'utilisation d'une bactérie artificiellement conçue sécrètant un pseudo-pétrole puissant.","fr")
locList.addLoc("tech_biofuel_refining_2","Raffinerie de biocarburant $enhanced$e","fr")
locList.addLoc("tech_biofuel_refining_3_desc","En manipulant les molécules organiques à une échelle nanométrique, nous sommes capables de créer un biocarburant bien plus puissant.","fr")
locList.addLoc("tech_biofuel_refining_3","Synthèse de biocarburant $advanced$e","fr")
locList.addLoc("tech_biofuel_refining_4_desc","Des méthodes de synthèse $advanced$es permettent de créer un biocarburant solide, ce qui rend le produit fini plus aisément transportable et bien plus puissant.","fr")
locList.addLoc("tech_biofuel_refining_4","Condensation Artificelle de Biocarburant","fr")
locList.addLoc("tech_biofuel_refining_5_desc","L'utilisation de machinerie à la précision picométrique nous permet de synthétiser du biocarburant sans générer de déchets.","fr")
locList.addLoc("tech_biofuel_refining_5","Synthèse de biocarburant $optimal$e","fr")
locList.addLoc("tech_power_plant_5_desc","L'utilisation de catalyse quantique nous permet de générer des quantités immenses d'énergie.","fr")
locList.addLoc("tech_power_plant_5","Synthese d'isotopes quantiques","fr")
locList.addLoc("tech_mining_network_5_desc","L'utilisation de foreuses gravitoniques nous permet de pénétrer rapidement et avec précision les strates profondes.","fr")
locList.addLoc("tech_mining_network_5","Minage $superior$","fr")
locList.addLoc("tech_superior_agriculture_desc","L'utilisation de terre nanoactive nous permet de faire posuser une quantité incroyable de cultures.","fr")
locList.addLoc("tech_superior_agriculture","Agriculture $superior$e","fr")
locList.addLoc("tech_biolab_4_desc","Considérer la temporalité comme un continuum holistique singulier nous permet de traiter des phénomènes à première vue disparates comme fondamentalement interconnectés.","fr")
locList.addLoc("tech_biolab_4","Psycho-Histoire Holistique","fr")
locList.addLoc("tech_physics_lab_4_desc","La théorie a atteint un stade où nous pouvons commencer les recherches sur la théorie Oméga, qui est capable de décrire non seulement notre univers, mais aussi des dimensions parallèles.","fr")
locList.addLoc("tech_physics_lab_4","Théorie Oméga","fr")
locList.addLoc("tech_engineering_lab_4_desc","Nos connaissances en physique ont atteint un point où nous sommes capable d'entamer la création de nanomatériel auto-remodelable et auto-adaptable.","fr")
locList.addLoc("tech_engineering_lab_4","Théories de la matière intelligente","fr")
locList.addLoc("tech_agricultural_processing_1_desc","Les Nanotechnologies, qui était à l'origines développées pour améliorer nos bases spatiales, nous permettent d'augmenter de manière significative la production de nos fermes et $hydroponic_farm$s.","fr")
locList.addLoc("tech_agricultural_processing_1","Transformation agricole $advanced$e","fr")
locList.addLoc("tech_agricultural_processing_2_desc","L'utilisation de technologies robotiques $advanced$es nous permet d'automatiser et améliorer toujours plus la transformation de matière organique en nourriture.","fr")
locList.addLoc("tech_agricultural_processing_2","Transformation agricole $superior$e","fr")
locList.addLoc("tech_hyperstorage_1","Hyperstockage","fr")
locList.addLoc("tech_hyperstorage_1_desc","Définir le stockage comme un problème scientifique ouvre la voie à l'émergence de nouveaux paradigmes.","fr")
locList.addLoc("tech_hyperstorage_2","Hyperstockage $advanced$","fr")
locList.addLoc("tech_hyperstorage_2_desc","Des progrès récents dans l'étude du stockage nanométrique augmentent de manière substentielle l'efficacité de nos complexes d'hyperstockage.","fr")
locList.addLoc("tech_hyperstorage_3","Hyperstockage $superior$","fr")
locList.addLoc("tech_hyperstorage_3_desc","Des progrès récents dans l'étude de l'entropie augmentent encore plus l'efficacité de nos complexes d'hyperstockage.","fr")

locList.addLoc("cgm_buildings_text","Core Game Mechanics: Buildings","fr")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_name","Activer les bâtiments de CGM","fr")
locList.addLoc("cgm_buildings_preset_enable_new_building_content_desc","Cette option active la refonte des bâtiments de production de ressources du mod CGM. Tous les bâtiments de production standard du jeu de base, ex les réseaux miniers ou les centrales énergétiques, sont automatiquement remplacées et les technologies nécessaires sont automatiquement débloquées. \n Notez cependant que cette option n'est disponible qu'à la création d'une partie et ne pourra pas être annulée.","fr")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_name","Garder les bâtiments du jeu de base","fr")
locList.addLoc("cgm_buildings_preset_keep_vanilla_building_content_desc","Cette option indique au jeu d'utiliser les bâtiments de production du jeu de base. Aucun changements ne seront apportés aux bâtiments ni aux technologies. Choisir cette option débloquera d'autres options de configurations plus loin.","fr")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_name","Activer les statistiques remaniées pour les bâtiments","fr")
locList.addLoc("cgm_buildings_option_enable_overhauled_vanilla_building_stats_desc","Cette option active les statistiques remaniées pour les bâtiments. Certains bâtiments ont différents rendements de production, des modificateurs planétaires, etc... par rapport au jeu de base. Cette option peut être activée/désactiver à volonté en milieu de partie.","fr")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_name","Désactiver les statistiques remaniées pour les bâtiments","fr")
locList.addLoc("cgm_buildings_option_disable_overhauled_vanilla_building_stats_desc","Cette option désactive les statistiques remaniées. Le contenu du jeu de base conservera les mêmes statistiques.","fr")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_name","Configuration avancée des bâtiments","fr")
locList.addLoc("cgm_buildings_option_advanced_building_configuration_desc","Cette option ouvre le menu de configuration avancée des bâtiments, qui permet de changer le coût et le temps de construction de catégories spécifiques de bâtiments.","fr")
locList.addLoc("cgm_main_menu_title","Menu principal CGM","fr")
locList.addLoc("cgm_main_menu_desc","Ce menu permet de choisir si vous souhaitez jouer ave cles bâtiments de production de ressource du jeu de base ou la version CGM. Ce choix est disponible uniquement à la création d'une partie.","fr")
locList.addLoc("cgm_main_menu_header","Core Game Mechanics","fr")
locList.addLoc("cgm_main_menu_close_name","Fermer le menu","fr")
locList.addLoc("cgm_main_menu_close_desc","Fermer le menu","fr")

### Strategic Resources

locList.addLoc("sr_megastructure_node","Node de Mégastructure","fr")
locList.addLoc("sr_megastructure_node_desc","Les nodes de Mégastructure représentent des junctions structurelles permettant le développement de la matrice énergétique de la structure.","fr")


### Modifiers

locList.addLoc("capital_building_build_cost_mult","Coût de construction des bâtiments de Capitale.","fr")
locList.addLoc("capital_building_construction_speed_mult","Vitesse de construction des bâtiments de Capitale.","fr")
locList.addLoc("empire_unique_building_build_cost_mult","Coût de construction des bâtiments unique de l'empire.","fr")
locList.addLoc("empire_unique_building_construction_speed_mult","Vitesse de construction des bâtiments unique de l'empire.","fr")
locList.addLoc("planet_unique_building_build_cost_mult","Coût de construction des bâtiments unique de la planète.","fr")
locList.addLoc("planet_unique_building_construction_speed_mult","Vitesse de construction des bâtiments unique de la planète.","fr")
locList.addLoc("military_building_build_cost_mult","Coût de construction des bâtiments militaires.","fr")
locList.addLoc("military_building_construction_speed_mult","Vitesse de construction des bâtiments militaires.","fr")
locList.addLoc("standard_resource_building_build_cost_mult","Coût de construction des bâtiments de production de ressources standard.","fr")
locList.addLoc("standard_resource_building_construction_speed_mult","Vitesse de construction des bâtiments de production de ressources standard.","fr")
locList.addLoc("research_resource_building_build_cost_mult","Coût de construction des centres de recherche.","fr")
locList.addLoc("research_resource_building_construction_speed_mult","Vitesse de construction des centres de recherche.","fr")
locList.addLoc("unity_resource_building_build_cost_mult","Coût de construction des bâtiments de production de ressources d'Unité.","fr")
locList.addLoc("unity_resource_building_construction_speed_mult","Vitesse de construction des bâtiments de production de ressources d'Unité.","fr")
locList.addLoc("special_resource_building_build_cost_mult","Coût de construction des bâtiments spéciaux.","fr")
locList.addLoc("special_resource_building_construction_speed_mult","Vitesse de construction des bâtiments spéciaux.","fr")
locList.addLoc("replicator_building_build_cost_mult","Coût de construction des réplicateurs.","fr")
locList.addLoc("replicator_building_construction_speed_mult","Vitesse de construction des réplicateurs.","fr")

### Triggered Planet Modifiers Keys

locList.addLoc("capital_3_resource_bonus_modifier","Bonus de Capitale d'empire de niveau 5","fr")
locList.addLoc("capital_3_resource_bonus_modifier_desc","Ce bonus spécial provient des bâtiments de production de niveau 5 sur une planète Capitale.","fr")
locList.addLoc("power_plant_5_regular_capital_modifier","Bonus aux centrales énergétiques de Capitale d'empire de niveau 5","fr")
locList.addLoc("power_plant_5_ringworld_capital_modifier","Bonus aux centrales énergétiques de Capitale d'empire de niveau 5 (Anneau-Monde)","fr")
locList.addLoc("mining_network_5_regular_capital_modifier","Bonus aux centres miniers de Capitale d'empire de niveau 5","fr")
locList.addLoc("mining_network_5_ringworld_capital_modifier","Bonus aux centres miniers de Capitale d'empire de niveau 5 (Anneau-Monde)","fr")
locList.addLoc("hydroponics_farm_5_regular_capital_modifier","Bonus aux fermes hydroponiques de Capitale","fr")
locList.addLoc("hydroponics_farm_5_ringworld_capital_modifier","Bonus aux fermes hydroponiques de Capitale (Anneau-Monde)","fr")
locList.addLoc("engineering_facility_4_regular_capital_modifier","Bonus aux centres d'ingénierie de Capitale d'empire de niveau 5","fr")
locList.addLoc("engineering_facility_4_ringworld_capital_modifier","Bonus aux centres d'ingénierie de Capitale d'empire de niveau 5 (Anneau-Monde)","fr")
locList.addLoc("physics_lab_4_regular_capital_modifier","Bonus aux laboratoires de physique de Capitale d'empire de niveau 5","fr")
locList.addLoc("physics_lab_4_ringworld_capital_modifier","Bonus aux laboratoires de physique de Capitale d'empire de niveau 5 (Anneau-Monde)","fr")
locList.addLoc("biolab_4_regular_capital_modifier","Bonus aux biolabs de Capitale d'empire de niveau 5","fr")
locList.addLoc("biolab_4_ringworld_capital_modifier","Bonus aux biolabs de Capitale d'empire de niveau 5 (Anneau-Monde)","fr")

### Building Localisations

locList.addLoc("mining_complex","Complexe Minier","fr")
locList.addLoc("mining_complex_desc","Les complexes miniers sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants des minéraux £minerals. Leur rendement de production de ressource de base dépend du niveau spécifique du bâtiment §H+200%§! de mineraux £minerals sur la case sur lesquels ils sont construits.","fr")
locList.addLoc("farming_complex","Exploitation agricole","fr")
locList.addLoc("farming_complex_desc","Les exploitations agricoles sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants de la nourriture £food. Leur rendement de production de ressource de base dépend du niveau spécifique du bâtiment §H+200%§! de nourriture £food sur la case sur lesquels ils sont construits.","fr")
locList.addLoc("isotope_refinery","Raffinerie d'isotope","fr")
locList.addLoc("isotope_refinery_desc","Les raffineries d'isotope sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants de l'énergie £energy. Leur rendement de production de ressource de base dépend du niveau spécifique du bâtiment §H+200%§! d'énergie £energy sur la case sur lesquels ils sont construits.","fr")
locList.addLoc("biofuel_refinery","Raffinerie de Biofuel","fr")
locList.addLoc("biofuel_refinery_desc","Les raffineries de biofuel sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants de la nourriture £food. Leur rendement de production de ressource de base dépend du niveau spécifique du bâtiment §H+200%§! de nourriture £food sur la case sur lesquels ils sont construits pour les convertir en énergie £energy.","fr")
locList.addLoc("society_lab","Laboratoire de Société","fr")
locList.addLoc("society_lab_desc","Les laboratoires de société sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants de la recherche de société £society. Leur rendement de production de ressource de base dépend du niveau spécifique du bâtiment §H+200%§! de recherche de société £society sur la case sur lesquels ils sont construits.","fr")
locList.addLoc("physics_lab","Laboratoire de physique","fr")
locList.addLoc("physics_lab_desc","Les laboratoires de physique sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants de la recherche physique £physics. Leur rendement de production de ressource de base dépend du niveau spécifique du bâtiment §H+200%§! de recherche physique £physics sur la case sur lesquels ils sont construits.","fr")
locList.addLoc("engineering_lab","Laboratoire d'ingénierie","fr")
locList.addLoc("engineering_lab_desc","Les laboratoires d'ingénierie sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants de la recherche d'ingénierie £engineering. Leur rendement de production de ressource de base dépend du niveau spécifique du bâtiment §H+200%§! de recherche d'ingénierie £engineering sur la case sur lesquels ils sont construits.","fr")
locList.addLoc("energy_matter_converter","Convertisseur Energie-Matière","fr")
locList.addLoc("energy_matter_converter_desc","Les convertisseurs Energie-Matière sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants un node de mégastructure £megastructure_node. Ils ont un rendement statique de §H§H+3§!§! minéraux £minerals mais ils donnent un puissant bonus d'adjacence relatif au nombre de nodes de mégastructure £megastructure_node sur la case sur laquelle il est construit ainsi que son niveau.","fr")
locList.addLoc("energy_conduit","Conduit d'énergie","fr")
locList.addLoc("energy_conduit_desc","Les conduits d'énergie sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants un node de mégastructure £megastructure_node. Ils ont un rendement statique de §H+3§! énergie £energy mais ils donnent un puissant bonus d'adjacence relatif au nombre de nodes de mégastructure £megastructure_node sur la case sur laquelle il est construit ainsi que son niveau.","fr")
locList.addLoc("food_replicator","Réplicateur de nourriture","fr")
locList.addLoc("food_replicator_desc","Les réplicateurs de nourriture sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants un node de mégastructure £megastructure_node. Ils ont un rendement statique de §H+3§! nourriture £food mais ils donnent un puissant bonus d'adjacence relatif au nombre de nodes de mégastructure £megastructure_node sur la case sur laquelle il est construit ainsi que son niveau.","fr")
locList.addLoc("computational_array","Réseau de calcul","fr")
locList.addLoc("computational_array_desc","Les réseaux de calcul sont des bâtiments §Hrestreints à une case§! qui peuvent uniquement être construit sur des cases possédants un node de mégastructure £megastructure_node. Ils ont un rendement statique de §H+1/+1/+1§! société £society, physique £physics et ingénierie £engineering mais ils donnent un puissant bonus d'adjacence à tous les bâtiments de recherche relatif au nombre de nodes de mégastructure £megastructure_node sur la case sur laquelle il est construit ainsi que son niveau.","fr")
locList.addLoc("economic_district","District économique","fr")
locList.addLoc("economic_district_desc","Les districts économiques sont des bâtiments de production d'énergie £energy sans restriction de case. Ces bâtiments représentent des centres commerciaux et des zones de développement économique.  Ils ont aussi bien un rendement de production de base qu'un rendement statique relatif au niveau spécifique du bâtiment.","fr")
locList.addLoc("manufacturing_complex","Complexe Manufacturier","fr")
locList.addLoc("manufacturing_complex_desc","Les Complexe Manufacturiers sont des bâtiments de production de minéraux £minerals sans restriction de case. Ces bâtiments sont des centres industriels et de développement.  Ils ont aussi bien un rendement de production de base qu'un rendement statique relatif au niveau spécifique du bâtiment.","fr")
locList.addLoc("hydroponic_farm","Fermes Hydroponiques","fr")
locList.addLoc("hydroponic_farm_desc","Les Fermes Hydroponiques sont des bâtiments de production de nourriture £food sans restriction de case. Ces bâtiments représentent des biosphères aux environnements rigoureusement contrôlés dédiés à la production de nourriture.  Ils ont aussi bien un rendement de production de base qu'un rendement statique relatif au niveau spécifique du bâtiment.","fr")
locList.addLoc("sociological_campus","Campus de Sociologie","fr")
locList.addLoc("sociological_campus_desc","Les Campus de Sociologie sont des centres de recherche sociétale £society sans restriction de case.  Ils ont aussi bien un rendement de production de base qu'un rendement statique relatif au niveau spécifique du bâtiment.","fr")
locList.addLoc("physics_campus","Campus de Physique","fr")
locList.addLoc("physics_campus_desc","Les Campus de Physique sont des centres de recherche en physique £physics sans restriction de case.  Ils ont aussi bien un rendement de production de base qu'un rendement statique relatif au niveau spécifique du bâtiment.","fr")
locList.addLoc("engineering_campus","Campus d'Ingénierie","fr")
locList.addLoc("engineering_campus_desc","Les Campus d'Ingénierie sont des centres de recherche en ingénierie £engineering sans restriction de case.  Ils ont aussi bien un rendement de production de base qu'un rendement statique relatif au niveau spécifique du bâtiment.","fr")
locList.addLoc("agricultural_processor","Transformateur agricole","fr")
locList.addLoc("agricultural_processor_desc","Les transformateurs agricoles produisent un peu de nourriture £food de manière autonome, mais plus important, ils augmentent la production globale de nourriture £food de la planète.","fr")
locList.addLoc("hyperstorage_facility","Installation d'Hyperstockage","fr")
locList.addLoc("hyperstorage_facility_desc","Les installations d'Hyperstockage utilisent des technologies de pointe dans les domaines de la stase et de la manipulation du vide pour stocker du matériel.  Bien que ces bâtiments produisent une petite quantité de minéraux £minerals pour les empires machines ainsi que de la nourriture £food et des minéraux £minerals pour les empires organiques, leur force réside dans le bonus d'adjacence offert aux bâtiments produisant de la nourriture £food, des minéraux £minerals et de l'énergie £energy. Ce bonus est proportionnel au niveau du bâtiment. De plus, quand un empire subit un §Rdéficit de minéraux§!, un §Rdéficit d'énergie§! ou, dans le cas d'empires organiques, une §Rfamine§!, les installations d'Hyperstockage vont produire une grosse quantité de G§une à deux des ressources manquantes§!.","fr")

### Generic Keys - these are used for the different variations of the buildings
locList.addLoc("cgm_building_mining_complex_1","$mining_complex$ I","fr")
locList.addLoc("cgm_building_mining_complex_1_desc","$basic$ $mining_complex$.\n\n$mining_complex_desc$","fr")
locList.addLoc("cgm_building_mining_complex_2","$mining_complex$ II","fr")
locList.addLoc("cgm_building_mining_complex_2_desc","$improved$ $mining_complex$.\n\n$mining_complex_desc$","fr")
locList.addLoc("cgm_building_mining_complex_3","$mining_complex$ III","fr")
locList.addLoc("cgm_building_mining_complex_3_desc","$enhanced$ $mining_complex$.\n\n$mining_complex_desc$","fr")
locList.addLoc("cgm_building_mining_complex_4","$mining_complex$ IV","fr")
locList.addLoc("cgm_building_mining_complex_4_desc","$advanced$ $mining_complex$.\n\n$mining_complex_desc$","fr")
locList.addLoc("cgm_building_mining_complex_5","$mining_complex$ V","fr")
locList.addLoc("cgm_building_mining_complex_5_desc","$superior$ $mining_complex$.\n\n$mining_complex_desc$","fr")
locList.addLoc("cgm_building_farming_complex_1","$farming_complex$ I","fr")
locList.addLoc("cgm_building_farming_complex_1_desc","$basic$ $farming_complex$.\n\n$farming_complex_desc$","fr")
locList.addLoc("cgm_building_farming_complex_2","$farming_complex$ II","fr")
locList.addLoc("cgm_building_farming_complex_2_desc","$improved$ $farming_complex$.\n\n$farming_complex_desc$","fr")
locList.addLoc("cgm_building_farming_complex_3","$farming_complex$ III","fr")
locList.addLoc("cgm_building_farming_complex_3_desc","$enhanced$ $farming_complex$.\n\n$farming_complex_desc$","fr")
locList.addLoc("cgm_building_farming_complex_4","$farming_complex$ IV","fr")
locList.addLoc("cgm_building_farming_complex_4_desc","$advanced$ $farming_complex$.\n\n$farming_complex_desc$","fr")
locList.addLoc("cgm_building_farming_complex_5","$farming_complex$ V","fr")
locList.addLoc("cgm_building_farming_complex_5_desc","$superior$ $farming_complex$.\n\n$farming_complex_desc$","fr")
locList.addLoc("cgm_building_isotope_refinery_1","$isotope_refinery$ I","fr")
locList.addLoc("cgm_building_isotope_refinery_1_desc","$basic$ $isotope_refinery$.\n\n$isotope_refinery_desc$","fr")
locList.addLoc("cgm_building_isotope_refinery_2","$isotope_refinery$ II","fr")
locList.addLoc("cgm_building_isotope_refinery_2_desc","$improved$ $isotope_refinery$.\n\n$isotope_refinery_desc$","fr")
locList.addLoc("cgm_building_isotope_refinery_3","$isotope_refinery$ III","fr")
locList.addLoc("cgm_building_isotope_refinery_3_desc","$enhanced$ $isotope_refinery$.\n\n$isotope_refinery_desc$","fr")
locList.addLoc("cgm_building_isotope_refinery_4","$isotope_refinery$ IV","fr")
locList.addLoc("cgm_building_isotope_refinery_4_desc","$advanced$ $isotope_refinery$.\n\n$isotope_refinery_desc$","fr")
locList.addLoc("cgm_building_isotope_refinery_5","$isotope_refinery$ V","fr")
locList.addLoc("cgm_building_isotope_refinery_5_desc","$superior$ $isotope_refinery$.\n\n$isotope_refinery_desc$","fr")
locList.addLoc("cgm_building_biofuel_refinery_1","$biofuel_refinery$ I","fr")
locList.addLoc("cgm_building_biofuel_refinery_1_desc","$basic$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","fr")
locList.addLoc("cgm_building_biofuel_refinery_2","$biofuel_refinery$ II","fr")
locList.addLoc("cgm_building_biofuel_refinery_2_desc","$improved$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","fr")
locList.addLoc("cgm_building_biofuel_refinery_3","$biofuel_refinery$ III","fr")
locList.addLoc("cgm_building_biofuel_refinery_3_desc","$enhanced$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","fr")
locList.addLoc("cgm_building_biofuel_refinery_4","$biofuel_refinery$ IV","fr")
locList.addLoc("cgm_building_biofuel_refinery_4_desc","$advanced$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","fr")
locList.addLoc("cgm_building_biofuel_refinery_5","$biofuel_refinery$ V","fr")
locList.addLoc("cgm_building_biofuel_refinery_5_desc","$superior$ $biofuel_refinery$.\n\n$biofuel_refinery_desc$","fr")
locList.addLoc("cgm_building_society_lab_1","$society_lab$ I","fr")
locList.addLoc("cgm_building_society_lab_1_desc","$basic$ $society_lab$.\n\n$society_lab_desc$","fr")
locList.addLoc("cgm_building_society_lab_2","$society_lab$ II","fr")
locList.addLoc("cgm_building_society_lab_2_desc","$improved$ $society_lab$.\n\n$society_lab_desc$","fr")
locList.addLoc("cgm_building_society_lab_3","$society_lab$ III","fr")
locList.addLoc("cgm_building_society_lab_3_desc","$enhanced$ $society_lab$.\n\n$society_lab_desc$","fr")
locList.addLoc("cgm_building_society_lab_4","$society_lab$ IV","fr")
locList.addLoc("cgm_building_society_lab_4_desc","$advanced$ $society_lab$.\n\n$society_lab_desc$","fr")
locList.addLoc("cgm_building_society_lab_5","$society_lab$ V","fr")
locList.addLoc("cgm_building_society_lab_5_desc","$superior$ $society_lab$.\n\n$society_lab_desc$","fr")
locList.addLoc("cgm_building_physics_lab_1","$physics_lab$ I","fr")
locList.addLoc("cgm_building_physics_lab_1_desc","$basic$ $physics_lab$.\n\n$physics_lab_desc$","fr")
locList.addLoc("cgm_building_physics_lab_2","$physics_lab$ II","fr")
locList.addLoc("cgm_building_physics_lab_2_desc","$improved$ $physics_lab$.\n\n$physics_lab_desc$","fr")
locList.addLoc("cgm_building_physics_lab_3","$physics_lab$ III","fr")
locList.addLoc("cgm_building_physics_lab_3_desc","$enhanced$ $physics_lab$.\n\n$physics_lab_desc$","fr")
locList.addLoc("cgm_building_physics_lab_4","$physics_lab$ IV","fr")
locList.addLoc("cgm_building_physics_lab_4_desc","$advanced$ $physics_lab$.\n\n$physics_lab_desc$","fr")
locList.addLoc("cgm_building_physics_lab_5","$physics_lab$ V","fr")
locList.addLoc("cgm_building_physics_lab_5_desc","$superior$ $physics_lab$.\n\n$physics_lab_desc$","fr")
locList.addLoc("cgm_building_engineering_lab_1","$engineering_lab$ I","fr")
locList.addLoc("cgm_building_engineering_lab_1_desc","$basic$ $engineering_lab$.\n\n$engineering_lab_desc$","fr")
locList.addLoc("cgm_building_engineering_lab_2","$engineering_lab$ II","fr")
locList.addLoc("cgm_building_engineering_lab_2_desc","$improved$ $engineering_lab$.\n\n$engineering_lab_desc$","fr")
locList.addLoc("cgm_building_engineering_lab_3","$engineering_lab$ III","fr")
locList.addLoc("cgm_building_engineering_lab_3_desc","$enhanced$ $engineering_lab$.\n\n$engineering_lab_desc$","fr")
locList.addLoc("cgm_building_engineering_lab_4","$engineering_lab$ IV","fr")
locList.addLoc("cgm_building_engineering_lab_4_desc","$advanced$ $engineering_lab$.\n\n$engineering_lab_desc$","fr")
locList.addLoc("cgm_building_engineering_lab_5","$engineering_lab$ V","fr")
locList.addLoc("cgm_building_engineering_lab_5_desc","$superior$ $engineering_lab$.\n\n$engineering_lab_desc$","fr")
locList.addLoc("cgm_building_energy_matter_converter_1","$energy_matter_converter$ I","fr")
locList.addLoc("cgm_building_energy_matter_converter_1_desc","$basic$ $energy_matter_converter$.\n\n$energy_matter_converter_desc$","fr")
locList.addLoc("cgm_building_energy_matter_converter_2","$energy_matter_converter$ II","fr")
locList.addLoc("cgm_building_energy_matter_converter_2_desc","$improved$ $energy_matter_converter$.\n\n$energy_matter_converter_desc$","fr")
locList.addLoc("cgm_building_energy_matter_converter_3","$energy_matter_converter$ III","fr")
locList.addLoc("cgm_building_energy_matter_converter_3_desc","$enhanced$ $energy_matter_converter$.\n\n$energy_matter_converter_desc$","fr")
locList.addLoc("cgm_building_energy_conduit_1","$energy_conduit$ I","fr")
locList.addLoc("cgm_building_energy_conduit_1_desc","$basic$ $energy_conduit$.\n\n$energy_conduit_desc$","fr")
locList.addLoc("cgm_building_energy_conduit_2","$energy_conduit$ II","fr")
locList.addLoc("cgm_building_energy_conduit_2_desc","$improved$ $energy_conduit$.\n\n$energy_conduit_desc$","fr")
locList.addLoc("cgm_building_energy_conduit_3","$energy_conduit$ III","fr")
locList.addLoc("cgm_building_energy_conduit_3_desc","$enhanced$ $energy_conduit$.\n\n$energy_conduit_desc$","fr")
locList.addLoc("cgm_building_food_replicator_1","$food_replicator$ I","fr")
locList.addLoc("cgm_building_food_replicator_1_desc","$basic$ $food_replicator$.\n\n$food_replicator_desc$","fr")
locList.addLoc("cgm_building_food_replicator_2","$food_replicator$ II","fr")
locList.addLoc("cgm_building_food_replicator_2_desc","$improved$ $food_replicator$.\n\n$food_replicator_desc$","fr")
locList.addLoc("cgm_building_food_replicator_3","$food_replicator$ III","fr")
locList.addLoc("cgm_building_food_replicator_3_desc","$enhanced$ $food_replicator$.\n\n$food_replicator_desc$","fr")
locList.addLoc("cgm_building_computational_array_1","$computational_array$ I","fr")
locList.addLoc("cgm_building_computational_array_1_desc","$basic$ $computational_array$.\n\n$computational_array_desc$","fr")
locList.addLoc("cgm_building_computational_array_2","$computational_array$ II","fr")
locList.addLoc("cgm_building_computational_array_2_desc","$improved$ $computational_array$.\n\n$computational_array_desc$","fr")
locList.addLoc("cgm_building_computational_array_3","$computational_array$ III","fr")
locList.addLoc("cgm_building_computational_array_3_desc","$enhanced$ $computational_array$.\n\n$computational_array_desc$","fr")

#### Building Localisations
locList.addLoc("building_economic_district_1","$economic_district$ I","fr")
locList.addLoc("building_economic_district_1_desc","$basic$ $economic_district$.\n\n$economic_district_desc$","fr")
locList.addLoc("building_economic_district_2","$economic_district$ II","fr")
locList.addLoc("building_economic_district_2_desc","$improved$ $economic_district$.\n\n$economic_district_desc$","fr")
locList.addLoc("building_economic_district_3","$economic_district$ III","fr")
locList.addLoc("building_economic_district_3_desc","$enhanced$ $economic_district$.\n\n$economic_district_desc$","fr")
locList.addLoc("building_economic_district_4","$economic_district$ IV","fr")
locList.addLoc("building_economic_district_4_desc","$advanced$ $economic_district$.\n\n$economic_district_desc$","fr")
locList.addLoc("building_economic_district_5","$economic_district$ V","fr")
locList.addLoc("building_economic_district_5_desc","$superior$ $economic_district$.\n\n$economic_district_desc$","fr")
locList.addLoc("building_manufacturing_complex_1","$manufacturing_complex$ I","fr")
locList.addLoc("building_manufacturing_complex_1_desc","$basic$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","fr")
locList.addLoc("building_manufacturing_complex_2","$manufacturing_complex$ II","fr")
locList.addLoc("building_manufacturing_complex_2_desc","$improved$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","fr")
locList.addLoc("building_manufacturing_complex_3","$manufacturing_complex$ III","fr")
locList.addLoc("building_manufacturing_complex_3_desc","$enhanced$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","fr")
locList.addLoc("building_manufacturing_complex_4","$manufacturing_complex$ IV","fr")
locList.addLoc("building_manufacturing_complex_4_desc","$advanced$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","fr")
locList.addLoc("building_manufacturing_complex_5","$manufacturing_complex$ V","fr")
locList.addLoc("building_manufacturing_complex_5_desc","$superior$ $manufacturing_complex$.\n\n$manufacturing_complex_desc$","fr")
locList.addLoc("building_hydroponic_farm_1","$hydroponic_farm$ I","fr")
locList.addLoc("building_hydroponic_farm_1_desc","$basic$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","fr")
locList.addLoc("building_hydroponic_farm_2","$hydroponic_farm$ II","fr")
locList.addLoc("building_hydroponic_farm_2_desc","$improved$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","fr")
locList.addLoc("building_hydroponic_farm_3","$hydroponic_farm$ III","fr")
locList.addLoc("building_hydroponic_farm_3_desc","$enhanced$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","fr")
locList.addLoc("building_hydroponic_farm_4","$hydroponic_farm$ IV","fr")
locList.addLoc("building_hydroponic_farm_4_desc","$advanced$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","fr")
locList.addLoc("building_hydroponic_farm_5","$hydroponic_farm$ V","fr")
locList.addLoc("building_hydroponic_farm_5_desc","$superior$ $hydroponic_farm$.\n\n$hydroponic_farm_desc$","fr")
locList.addLoc("building_sociological_campus_1","$sociological_campus$ I","fr")
locList.addLoc("building_sociological_campus_1_desc","$basic$ $sociological_campus$.\n\n$sociological_campus_desc$","fr")
locList.addLoc("building_sociological_campus_2","$sociological_campus$ II","fr")
locList.addLoc("building_sociological_campus_2_desc","$improved$ $sociological_campus$.\n\n$sociological_campus_desc$","fr")
locList.addLoc("building_sociological_campus_3","$sociological_campus$ III","fr")
locList.addLoc("building_sociological_campus_3_desc","$enhanced$ $sociological_campus$.\n\n$sociological_campus_desc$","fr")
locList.addLoc("building_sociological_campus_4","$sociological_campus$ IV","fr")
locList.addLoc("building_sociological_campus_4_desc","$advanced$ $sociological_campus$.\n\n$sociological_campus_desc$","fr")
locList.addLoc("building_sociological_campus_5","$sociological_campus$ V","fr")
locList.addLoc("building_sociological_campus_5_desc","$superior$ $sociological_campus$.\n\n$sociological_campus_desc$","fr")
locList.addLoc("building_physics_campus_1","$physics_campus$ I","fr")
locList.addLoc("building_physics_campus_1_desc","$basic$ $physics_campus$.\n\n$physics_campus_desc$","fr")
locList.addLoc("building_physics_campus_2","$physics_campus$ II","fr")
locList.addLoc("building_physics_campus_2_desc","$improved$ $physics_campus$.\n\n$physics_campus_desc$","fr")
locList.addLoc("building_physics_campus_3","$physics_campus$ III","fr")
locList.addLoc("building_physics_campus_3_desc","$enhanced$ $physics_campus$.\n\n$physics_campus_desc$","fr")
locList.addLoc("building_physics_campus_4","$physics_campus$ IV","fr")
locList.addLoc("building_physics_campus_4_desc","$advanced$ $physics_campus$.\n\n$physics_campus_desc$","fr")
locList.addLoc("building_physics_campus_5","$physics_campus$ V","fr")
locList.addLoc("building_physics_campus_5_desc","$superior$ $physics_campus$.\n\n$physics_campus_desc$","fr")
locList.addLoc("building_engineering_campus_1","$engineering_campus$ I","fr")
locList.addLoc("building_engineering_campus_1_desc","$basic$ $engineering_campus$.\n\n$engineering_campus_desc$","fr")
locList.addLoc("building_engineering_campus_2","$engineering_campus$ II","fr")
locList.addLoc("building_engineering_campus_2_desc","$improved$ $engineering_campus$.\n\n$engineering_campus_desc$","fr")
locList.addLoc("building_engineering_campus_3","$engineering_campus$ III","fr")
locList.addLoc("building_engineering_campus_3_desc","$enhanced$ $engineering_campus$.\n\n$engineering_campus_desc$","fr")
locList.addLoc("building_engineering_campus_4","$engineering_campus$ IV","fr")
locList.addLoc("building_engineering_campus_4_desc","$advanced$ $engineering_campus$.\n\n$engineering_campus_desc$","fr")
locList.addLoc("building_engineering_campus_5","$engineering_campus$ V","fr")
locList.addLoc("building_engineering_campus_5_desc","$superior$ $engineering_campus$.\n\n$engineering_campus_desc$","fr")
locList.addLoc("building_agricultural_processor_1","$agricultural_processor$ I","fr")
locList.addLoc("building_agricultural_processor_2","$agricultural_processor$ II","fr")
locList.addLoc("building_hyperstorage_facility_1","$hyperstorage_facility$ I","fr")
locList.addLoc("building_hyperstorage_facility_2","$hyperstorage_facility$ II","fr")
locList.addLoc("building_hyperstorage_facility_3","$hyperstorage_facility$ III","fr")

##### buildings that use a key for localisations

# Debug Resource - these can be turned on to expose the AI logic

locList.addLoc("sr_null_e_desc","REPLACE_ME","fr")
locList.addLoc("sr_null_e","Energy Building Tile","fr")
locList.addLoc("sr_null_en_desc","REPLACE_ME","fr")
locList.addLoc("sr_null_en","Engineering Building Tile","fr")
locList.addLoc("sr_null_f_desc","REPLACE_ME","fr")
locList.addLoc("sr_null_f","Food Building Tile","fr")
locList.addLoc("sr_null_m_desc","REPLACE_ME","fr")
locList.addLoc("sr_null_m","Minerals Building Tile","fr")
locList.addLoc("sr_null_py_desc","REPLACE_ME","fr")
locList.addLoc("sr_null_py","Physics Building Tile","fr")
locList.addLoc("sr_null_sc_desc","REPLACE_ME","fr")
locList.addLoc("sr_null_sc","Society Building Tile","fr")
locList.addLoc("sr_null_u_desc","REPLACE_ME","fr")
locList.addLoc("sr_null_u","Unity Building Tile","fr")

### Deposits - these do not actually require a localisation. The localisations below are just placeholder to remove error messages in CWTools

locList.addLoc("1_energy","REPLACE_ME","fr")
locList.addLoc("1_minerals","REPLACE_ME","fr")
locList.addLoc("1_food","REPLACE_ME","fr")
locList.addLoc("1_unity","REPLACE_ME","fr")
locList.addLoc("1_society_research","REPLACE_ME","fr")
locList.addLoc("1_physics_research","REPLACE_ME","fr")
locList.addLoc("1_engineering_research","REPLACE_ME","fr")
locList.addLoc("energy_building_tile","REPLACE_ME","fr")
locList.addLoc("minerals_building_tile","REPLACE_ME","fr")
locList.addLoc("food_building_tile","REPLACE_ME","fr")
locList.addLoc("unity_building_tile","REPLACE_ME","fr")
locList.addLoc("society_research_building_tile","REPLACE_ME","fr")
locList.addLoc("engineering_research_building_tile","REPLACE_ME","fr")
locList.addLoc("physics_research_building_tile","REPLACE_ME","fr")
locList.addLoc("special_resource_tile","REPLACE_ME","fr")
locList.addLoc("d_megastructure_node","REPLACE_ME","fr")
