locList.addLoc("locale_key","english","en")
locList.addLoc("pc_large_asteroid_moon","Large orbiting Asteroid","en")
locList.addLoc("pc_large_asteroid_moon_desc","Possibly an asteroid that was captured by this planet's gravity.\n\n","en")
locList.addLoc("pc_small_asteroid_moon","Small orbiting Asteroid","en")
locList.addLoc("pc_small_asteroid_moon_desc","Possibly an asteroid that was captured by this planet's gravity.\n\n","en")
locList.addLoc("pc_retinal","Retinal World","en")
locList.addLoc("pc_retinal_desc","These unusual purple worlds usually have temperate and humid climates, displaying dense vegetation that uses retinal instead of chlorophyll, possibly a result of having evolved around a star with low luminosity or as a gas-giant moon. Most Retinal worlds are tidally locked, but increased volcanic activity helps to keep conditions stable due to greenhouse effects.","en")
locList.addLoc("pc_retinal_habitability","Retinal Habitability","en")
locList.addLoc("pc_retinal_tile","Forested Terrain","en")
locList.addLoc("pc_retinal_tile_desc","Diverse forested terrain with a humid but cold climate.","en")
locList.addLoc("trait_pc_retinal_preference","Retinal World $preference$","en")
locList.addLoc("pc_greenhouse_hot","Hot Reducing World","en")
locList.addLoc("pc_greenhouse_hot_desc","A rocky planet with a thick, high pressure atmosphere. The gases in the atmosphere have caused a runaway greenhouse effect, creating very high surface temperatures.","en")
locList.addLoc("pc_greenhouse_cold","Cold Reducing World","en")
locList.addLoc("pc_greenhouse_cold_desc","A rocky planet with a dense atmosphere. Despite being far from the parent star, the gases in the atmosphere have caused a greenhouse effect, allowing exotic liquids such as methane and ethane to exist on the surface.","en")
locList.addLoc("pc_irradiated_terrestrial","Irradiated Terrestrial World","en")
locList.addLoc("pc_irradiated_terrestrial_desc","These terrestrial worlds have barren and irradiated surfaces, lacking a strong magnetosphere to protect it from its star's radiation. Despite harsh surface conditions, liquid oceans of water can be found that offer enough protection from radiation allowing some vegetation and life to exist.","en")
locList.addLoc("pc_irradiated_terrestrial_habitability","Irradiated Terrestrial Habitability","en")
locList.addLoc("pc_irradiated_terrestrial_tile","Irradiated Terrain","en")
locList.addLoc("pc_irradiated_terrestrial_tile_desc","Irradiated and barren terrain.","en")
locList.addLoc("trait_pc_irradiated_terrestrial_preference","Irradiated Terrestrial World $preference$","en")
locList.addLoc("pc_lush","Lush World","en")
locList.addLoc("pc_lush_desc","These lush worlds have a temperate climate with a nitrogen-oxygen atmosphere and a resilient ecosystem. Climate variation is very low, resulting in lush terrain dominating its land masses which are separated by mostly shallow seas. Cold and dry climates are only found near the poles and mountain tops, while deserts are usually non-existent as precepitation levels are similar in every latitude. This planet type can be considered perfect for any species that evolved in temperate worlds.","en")
locList.addLoc("pc_lush_habitability","Lush Habitability","en")
locList.addLoc("pc_lush_tile","Lush Terrain","en")
locList.addLoc("pc_lush_tile_desc","Fertile terrain with lush vegetation, providing perfect living conditions to any forms of life adapted to temperate climates.","en")
locList.addLoc("trait_pc_lush_preference","Lush World $preference$","en")
locList.addLoc("pc_geoplastic","Molten World","en")
locList.addLoc("pc_geoplastic_desc","These worlds represent the earliest stage in the formation of a habitable planet. The core and crust are completely molten, making the planet susceptible to solar winds and radiation, and subject to extremely high surface temperatures. The atmosphere is very thin and composed of hydrogen and helium. As the planet cools, the core and crust begin to harden and the planet can become Primordial if conditions are right.","en")
locList.addLoc("pc_geometallic","Primordial World","en")
locList.addLoc("pc_geometallic_desc","As a Molten world cools, the crust and core solidify and the planet can become Primordial if conditions are right. These barren worlds are witness to much geologic activity, steam expelled from volcanic eruptions condenses into water and forms the first shallow seas, in which bacteria may develop and ultimately thrive. As the core of a Primordial planet cools, the volcanic activity lessens and the planet eventually transitions to a more inhabitable class.","en")
locList.addLoc("pc_geocrystalline","Cambrian World","en")
locList.addLoc("pc_geocrystalline_desc","After the core of a Primordial planet is sufficiently cool, volcanic activity lessens and conditions for life improve. Oxygen and Nitrogen are present in some abundance in the atmosphere, giving rise to increasingly complex organisms such as primitive vegetation like algae, and animal akin to sponges and jellyfish. As the planet continues to cool, it can finally transition into the final stage of its evolution.","en")
locList.addLoc("pc_geocrystalline_habitability","Cambrian Habitability","en")
locList.addLoc("pc_geocrystalline_tile","Rocky Terrain","en")
locList.addLoc("pc_geocrystalline_tile_desc","Dry and rocky terrain with sparse vegetation.","en")
locList.addLoc("trait_pc_geocrystalline_preference","Cambrian World $preference$","en")
locList.addLoc("pc_geomorteus","Radiated World","en")
locList.addLoc("pc_geomorteus_desc","Small, rocky worlds located within a star system's hot zone. Unsuitable for humanoid life, these planets have highly unstable radiated surfaces. The thin atmospheres are composed primarily of helium and sodium. In the harsh daylight, temperatures can approach 450ยบ Celsius, because there is little atmosphere to retain that heat, it can get as cold as -200ยบ Celsius at night. No life forms have ever been observed on Radiated worlds.","en")
locList.addLoc("pc_dwarf_planet_asteroid","Dwarf Planetoid","en")
locList.addLoc("pc_dwarf_planet_asteroid_desc","A planetoid is a tiny world that generally does not meet the criteria for a planet, this includes moons, asteroids, and small planet-like objects. Dwarf planetoids can be composed of rock or ice, many are not even spherical, and have eccentric orbits cluttered with various even smaller objects.","en")
locList.addLoc("pc_gas_giant_hot","Ultra Giant","en")
locList.addLoc("pc_gas_giant_hot_desc","A large gaseous planet with an atmosphere primarily composed of hydrogen and helium. The planet is in close proximity to the parent star and so has a very high surface temperature and a short orbital period. The atmosphere is extreme and exotic due to the short period and long days, with intense winds and super-rotating equatorial jet streams.","en")
locList.addLoc("pc_ice_giant","Ice Giant","en")
locList.addLoc("pc_ice_giant_desc","These frozen giants are vastly different in composition from their gaseous brethren. The core is mostly rock and ice, surrounded by tenuous layers of water, methane, and ammonia. Additionally, the magnetic field is sharply inclined to the axis of rotation. These planets form on the fringe of a star system.","en")
locList.addLoc("pc_marginal","Warm Marginal World","en")
locList.addLoc("pc_marginal_desc","These marginal worlds, also known as Super-Earths, are generally similar to Terrestrial planets, but on a larger scale and with smaller water coverege. The Warm sub-class tends to be rocky and forested, and while they are suitable for life, the scarce water supply makes natural evolution more difficult.","en")
locList.addLoc("pc_marginal_habitability","Warm Marginal Habitability","en")
locList.addLoc("pc_marginal_tile","Temperate Terrain","en")
locList.addLoc("pc_marginal_tile_desc","Diverse forested terrain with a mild climate.","en")
locList.addLoc("trait_pc_marginal_preference","Warm Marginal World $preference$","en")
locList.addLoc("pc_irradiated_marginal","Irradiated Marginal World","en")
locList.addLoc("pc_irradiated_marginal_desc","These marginal worlds, also known as Super-Earths, have barren and irradiated surfaces, lacking a strong magnetosphere to protect them from their star's radiation. Despite harsh surface conditions, liquid bodies of water can be found that offer enough protection from radiation allowing some vegetation and life to exist under water.","en")
locList.addLoc("pc_irradiated_marginal_habitability","Irradiated Marginal Habitability","en")
locList.addLoc("pc_irradiated_marginal_tile","Irradiated Terrain","en")
locList.addLoc("pc_irradiated_marginal_tile_desc","Irradiated and barren terrain.","en")
locList.addLoc("trait_pc_irradiated_marginal_preference","Irradiated Marginal World $preference$","en")
locList.addLoc("pc_marginal_cold","Cold Marginal World","en")
locList.addLoc("pc_marginal_cold_desc","These marginal worlds, also known as Super-Earths, are generally similar to Terrestrial planets, but on a larger scale and with smaller water coverege. The Cold sub-class tends to be frigid and rocky, with large bodies of frozen water, except in lower latitudes where liquid water and vegetation can be found.","en")
locList.addLoc("pc_marginal_cold_habitability","Cold Marginal Habitability","en")
locList.addLoc("pc_marginal_cold_tile","Cold Terrain","en")
locList.addLoc("pc_marginal_cold_tile_desc","Snow-covered terrain with some vegetation.","en")
locList.addLoc("trait_pc_marginal_cold_preference","Cold Marginal World $preference$","en")
